PrimeCity_ShadyBuilding_1F_MapScripts::
	.byte 0


PrimeCity_ShadyBuilding_1F_EventScript_MessGuy::
	lock
	faceplayer
	msgbox PrimeCity_ShadyBuilding_1F_EventScript_MessGuy_Text_0
	release
	end


PrimeCity_ShadyBuilding_1F_EventScript_LizargunGuy::
	lock
	faceplayer
	msgbox PrimeCity_ShadyBuilding_1F_EventScript_LizargunGuy_Text_0
	release
	end


PrimeCity_ShadyBuilding_1F_EventScript_RoughNightGuy::
	lock
	faceplayer
	msgbox PrimeCity_ShadyBuilding_1F_EventScript_RoughNightGuy_Text_0
	release
	end


PrimeCity_ShadyBuilding_1F_EventScript_RiotaChampion::
	lock
	faceplayer
	msgbox PrimeCity_ShadyBuilding_1F_EventScript_RiotaChampion_Text_0
	release
	end


PrimeCity_ShadyBuilding_1F_EventScript_MessGuy_Text_0:
	.string "What?\nThe room's a mess?\pWe're students.\nWhat's your excuse, huh?\lHuh?\lHuh?\lHuh?\lThat's what I thought.$"

PrimeCity_ShadyBuilding_1F_EventScript_LizargunGuy_Text_0:
	.string "Apparently Charmeleon has a secret\nevolution called Lizargun.\pSounds cool, right?\nI bet my Charizard could beat it though.$"

PrimeCity_ShadyBuilding_1F_EventScript_RoughNightGuy_Text_0:
	.string "Urgh…\nDon't talk to me.\lLast night was crazy.\pI just wanna sit and eat ice cream,\nbut I've got a class later.$"

PrimeCity_ShadyBuilding_1F_EventScript_RiotaChampion_Text_0:
	.string "Hic…\nyou know kid, I'm Ríota's Champion.\pWhaaat, you don't believe me?\nGet out of here, you loser.$"
