VientoWalk_MapScripts::
	.byte 0


VientoWalk_EventScript_Sofia::
	trainerbattle_single TRAINER_G2_SOFIA, VientoWalk_EventScript_Sofia_Text_0, VientoWalk_EventScript_Sofia_Text_1
	msgbox VientoWalk_EventScript_Sofia_Text_2
	release
	end


VientoWalk_EventScript_Paula::
	trainerbattle_single TRAINER_G2_PAULA, VientoWalk_EventScript_Paula_Text_0, VientoWalk_EventScript_Paula_Text_1
	msgbox VientoWalk_EventScript_Paula_Text_2
	release
	end


VientoWalk_EventScript_Carlos::
	trainerbattle_single TRAINER_G2_CARLOS, VientoWalk_EventScript_Carlos_Text_0, VientoWalk_EventScript_Carlos_Text_1
	msgbox VientoWalk_EventScript_Carlos_Text_2
	release
	end


VientoWalk_EventScript_Estefani::
	trainerbattle_single TRAINER_G2_ESTEFANI, VientoWalk_EventScript_Estefani_Text_0, VientoWalk_EventScript_Estefani_Text_1
	msgbox VientoWalk_EventScript_Estefani_Text_2
	release
	end


VientoWalk_EventScript_Amanda::
	trainerbattle_single TRAINER_G2_AMANDA, VientoWalk_EventScript_Amanda_Text_0, VientoWalk_EventScript_Amanda_Text_1
	msgbox VientoWalk_EventScript_Amanda_Text_2
	release
	end


VientoWalk_EventScript_Nicolas::
	trainerbattle_single TRAINER_G2_NICOLAS, VientoWalk_EventScript_Nicolas_Text_0, VientoWalk_EventScript_Nicolas_Text_1
	msgbox VientoWalk_EventScript_Nicolas_Text_2
	release
	end


VientoWalk_EventScript_Merry::
	trainerbattle_single TRAINER_G2_MERRY, VientoWalk_EventScript_Merry_Text_0, VientoWalk_EventScript_Merry_Text_1
	msgbox VientoWalk_EventScript_Merry_Text_2
	release
	end


VientoWalk_EventScript_Anahi::
	trainerbattle_single TRAINER_G2_ANAHI, VientoWalk_EventScript_Anahi_Text_0, VientoWalk_EventScript_Anahi_Text_1
	msgbox VientoWalk_EventScript_Anahi_Text_2
	release
	end


VientoWalk_EventScript_Sofia_Text_0:
	.string "The smell of flowers in the air…\nIsn't it soothing?$"

VientoWalk_EventScript_Sofia_Text_1:
	.string "…How cruel…$"

VientoWalk_EventScript_Sofia_Text_2:
	.string "It seems like you can only\nfind Flabébé riding red flowers\laround here.$"

VientoWalk_EventScript_Paula_Text_0:
	.string "The wind calls to me!\nIt says to battle you!$"

VientoWalk_EventScript_Paula_Text_1:
	.string "Was the wind guiding me towards defeat?!$"

VientoWalk_EventScript_Paula_Text_2:
	.string "Maybe I should make my own decisions\ninstead of trusting the wind.$"

VientoWalk_EventScript_Carlos_Text_0:
	.string "Flowers bloom here all year round.\nI battle all year round, too!$"

VientoWalk_EventScript_Carlos_Text_1:
	.string "I also lose all year round…$"

VientoWalk_EventScript_Carlos_Text_2:
	.string "I need to head back to a\nPokémon Center!$"

VientoWalk_EventScript_Estefani_Text_0:
	.string "Are you ready to fight?\nNo?\lWell, I don't care.$"

VientoWalk_EventScript_Estefani_Text_1:
	.string "…Why?$"

VientoWalk_EventScript_Estefani_Text_2:
	.string "I'm a Picnicker, but I don't eat\nsandwiches and salads on my\lpicnics.\pI drink the tears of my opponents!$"

VientoWalk_EventScript_Amanda_Text_0:
	.string "Do you love your Pokémon?\nMe too!$"

VientoWalk_EventScript_Amanda_Text_1:
	.string "My love wasn't enough!$"

VientoWalk_EventScript_Amanda_Text_2:
	.string "Some Pokémon evolve when they feel\nclose enough to their Trainer.$"

VientoWalk_EventScript_Nicolas_Text_0:
	.string "Roam free, my avian comrades!$"

VientoWalk_EventScript_Nicolas_Text_1:
	.string "Beaten by a land-dweller?\nWhat is this?!$"

VientoWalk_EventScript_Nicolas_Text_2:
	.string "Flying above the clouds, on\nthe back of a bird Pokémon…\pIt's an indescribable feeling.$"

VientoWalk_EventScript_Merry_Text_0:
	.string "If you're a tuft of grass, then\nI'm the mower coming to cut\lyou down to size!$"

VientoWalk_EventScript_Merry_Text_1:
	.string "Aw, man!$"

VientoWalk_EventScript_Merry_Text_2:
	.string "If you use a Sun Stone, then\nCottonee will evolve into Whimsicott.$"

VientoWalk_EventScript_Anahi_Text_0:
	.string "You're cursed!\nI'm going to seal you away!$"

VientoWalk_EventScript_Anahi_Text_1:
	.string "Help!\nIt's breaking loose!$"

VientoWalk_EventScript_Anahi_Text_2:
	.string "I suppose I'll have to call\nin my Hex Maniac friends to\lpurify you!$"
