Route1_Text_FreddyIntro:
	.string "I'll reach the top with\n"
	.string "my awesome Pokémon!$"

Route1_Text_FreddyDefeated:
	.string "I can't believe this…$"

Route1_Text_FreddyPostBattle:
	.string "Just you wait!\n"
	.string "I'll be the best, I'll show you!$"

Route1_Text_LiamIntro:
	.string "Trainer spotted!\n"
	.string "Let's battle!$"

Route1_Text_LiamDefeated:
	.string "I thought that I'd win this one\n"
	.string "for sure…$"

Route1_Text_LiamPostBattle:
	.string "If you lock eyes with another\n"
	.string "Trainer, you have to battle.\l"
	.string "That's just common sense.$"

Route1_Text_NicoletIntro:
	.string "Cute Pokémon are my favourites!$"

Route1_Text_NicoletDefeated:
	.string "But they aren't always good in\n"
	.string "a battle…$"

Route1_Text_NicoletPostBattle:
	.string "Is your favourite Pokémon cute?$"

FableSquare_Text_HugoIntro:
	.string "Trainer spotted!\n"
	.string "Let's battle!$"

FableSquare_Text_HugoDefeated:
	.string "I thought that I'd win this one\n"
	.string "for sure…$"

FableSquare_Text_HugoPostBattle:
	.string "If you lock eyes with another\n"
	.string "Trainer, you have to battle.\l"
	.string "That's just common sense.$"

FableSquare_Text_MarthaIntro:
	.string "Cute Pokémon are my favourites!$"

FableSquare_Text_MarthaDefeated:
	.string "But they aren't always good in\n"
	.string "a battle…$"

FableSquare_Text_MarthaPostBattle:
	.string "Is your favourite Pokémon cute?$"

Route2_Text_DaanIntro:
	.string "Cute Pokémon are my favourites!$"

Route2_Text_DaanDefeated:
	.string "But they aren't always good in\n"
	.string "a battle…$"

Route2_Text_DaanPostBattle:
	.string "Is your favourite Pokémon cute?$"

Route2_Text_IngridIntro:
	.string "Cute Pokémon are my favourites!$"

Route2_Text_IngridDefeated:
	.string "But they aren't always good in\n"
	.string "a battle…$"

Route2_Text_IngridPostBattle:
	.string "Is your favourite Pokémon cute?$"

Route2_Text_LukasIntro:
	.string "Cute Pokémon are my favourites!$"

Route2_Text_LukasDefeated:
	.string "But they aren't always good in\n"
	.string "a battle…$"

Route2_Text_LukasPostBattle:
	.string "Is your favourite Pokémon cute?$"

Route2_Text_ChloeIntro:
	.string "Cute Pokémon are my favourites!$"

Route2_Text_ChloeDefeated:
	.string "But they aren't always good in\n"
	.string "a battle…$"

Route2_Text_ChloePostBattle:
	.string "Is your favourite Pokémon cute?$"

Route2_Text_HankIntro:
	.string "Cute Pokémon are my favourites!$"

Route2_Text_HankDefeated:
	.string "But they aren't always good in\n"
	.string "a battle…$"

Route2_Text_HankPostBattle:
	.string "Is your favourite Pokémon cute?$"
