Route1_EventScript_Freddy::
	trainerbattle_single TRAINER_FREDDY, Route1_Text_FreddyIntro, Route1_Text_FreddyDefeated
	msgbox Route1_Text_FreddyPostBattle, MSGBOX_AUTOCLOSE
	end

Route1_EventScript_Liam::
	trainerbattle_single TRAINER_LIAM, Route1_Text_LiamIntro, Route1_Text_LiamDefeated
	msgbox Route1_Text_LiamPostBattle, MSGBOX_AUTOCLOSE
	end

Route1_EventScript_Nicolet::
	trainerbattle_single TRAINER_NICOLET, Route1_Text_NicoletIntro, Route1_Text_NicoletDefeated
	msgbox Route1_Text_NicoletPostBattle, MSGBOX_AUTOCLOSE
	end

FableSquare_EventScript_Hugo::
	trainerbattle_single TRAINER_HUGO, FableSquare_Text_HugoIntro, FableSquare_Text_HugoDefeated
	msgbox FableSquare_Text_HugoPostBattle, MSGBOX_AUTOCLOSE
	end

FableSquare_EventScript_Martha::
	trainerbattle_single TRAINER_MARTHA, FableSquare_Text_MarthaIntro, FableSquare_Text_MarthaDefeated
	msgbox FableSquare_Text_MarthaPostBattle, MSGBOX_AUTOCLOSE
	end

Route2_EventScript_Daan::
	trainerbattle_single TRAINER_DAAN, Route2_Text_DaanIntro, Route2_Text_DaanDefeated
	msgbox Route2_Text_DaanPostBattle, MSGBOX_AUTOCLOSE
	end

Route2_EventScript_Ingrid::
	trainerbattle_single TRAINER_INGRID, Route2_Text_IngridIntro, Route2_Text_IngridDefeated
	msgbox Route2_Text_IngridPostBattle, MSGBOX_AUTOCLOSE
	end

Route2_EventScript_Lukas::
	trainerbattle_single TRAINER_LUKAS, Route2_Text_LukasIntro, Route2_Text_LukasDefeated
	msgbox Route2_Text_LukasPostBattle, MSGBOX_AUTOCLOSE
	end

Route2_EventScript_Chloe::
	trainerbattle_single TRAINER_CHLOE, Route2_Text_ChloeIntro, Route2_Text_ChloeDefeated
	msgbox Route2_Text_ChloePostBattle, MSGBOX_AUTOCLOSE
	end

Route2_EventScript_Hank::
	trainerbattle_single TRAINER_HANK, Route2_Text_HankIntro, Route2_Text_HankDefeated
	msgbox Route2_Text_HankPostBattle, MSGBOX_AUTOCLOSE
	end

