Route1_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route1_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

Route1_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

Route2_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

Route2_EventScript_ItemAntidote::
	finditem ITEM_ANTIDOTE
	end

Route2_EventScript_ItemTM07::
	finditem ITEM_TM07
	end

TwistedWoods_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

TwistedWoods_EventScript_ItemBigRoot::
	finditem ITEM_BIG_ROOT
	end

TwistedWoods_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

TwistedWoods_EventScript_ItemSilverPowder::
	finditem ITEM_SILVER_POWDER
	end

DotsyCity_EventScript_ItemSmokeBall::
	finditem ITEM_SMOKE_BALL
	end

Route3_Top_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

Route3_Top_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

Route3_Top_EventScript_ItemAwakening::
	finditem ITEM_AWAKENING
	end

Route3_Top_EventScript_ItemTM22::
	finditem ITEM_TM22
	end

GloomyCavern_EventScript_ItemXDefense::
	finditem ITEM_X_DEFENSE
	end

GloomyCavern_EventScript_ItemHardStone::
	finditem ITEM_HARD_STONE
	end

GloomyCavern_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

GloomyCavern_EventScript_ItemEverstone::
	finditem ITEM_EVERSTONE
	end

Route3_Bottom_EventScript_ItemBindingBand::
	finditem ITEM_BINDING_BAND
	end

Route3_Bottom_EventScript_ItemDireHit::
	finditem ITEM_DIRE_HIT
	end

Route3_Bottom_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

OakenCity_EventScript_ItemMiracleSeed::
	finditem ITEM_MIRACLE_SEED
	end
