RocarohaValley_MapScripts::
	.byte 0


RocarohaValley_EventScript_Santi::
	trainerbattle_single TRAINER_G2_SANTI, RocarohaValley_EventScript_Santi_Text_0, RocarohaValley_EventScript_Santi_Text_1
	msgbox RocarohaValley_EventScript_Santi_Text_2
	release
	end


RocarohaValley_EventScript_Lucia::
	trainerbattle_single TRAINER_G2_LUCIA, RocarohaValley_EventScript_Lucia_Text_0, RocarohaValley_EventScript_Lucia_Text_1
	msgbox RocarohaValley_EventScript_Lucia_Text_2
	release
	end


RocarohaValley_EventScript_Vicky::
	trainerbattle_single TRAINER_G2_VICKY, RocarohaValley_EventScript_Lucia_Text_0, RocarohaValley_EventScript_Lucia_Text_1
	msgbox RocarohaValley_EventScript_Lucia_Text_2
	release
	end


RocarohaValley_EventScript_Rafael::
	trainerbattle_single TRAINER_G2_RAFAEL, RocarohaValley_EventScript_Lucia_Text_0, RocarohaValley_EventScript_Lucia_Text_1
	msgbox RocarohaValley_EventScript_Lucia_Text_2
	release
	end


RocarohaValley_EventScript_Paolo::
	trainerbattle_single TRAINER_G2_PAOLO, RocarohaValley_EventScript_Lucia_Text_0, RocarohaValley_EventScript_Lucia_Text_1
	msgbox RocarohaValley_EventScript_Lucia_Text_2
	release
	end


RocarohaValley_EventScript_Martin::
	trainerbattle_single TRAINER_G2_MARTIN, RocarohaValley_EventScript_Lucia_Text_0, RocarohaValley_EventScript_Lucia_Text_1
	msgbox RocarohaValley_EventScript_Lucia_Text_2
	release
	end


RocarohaValley_EventScript_Luisa::
	trainerbattle_single TRAINER_G2_LUISA, RocarohaValley_EventScript_Lucia_Text_0, RocarohaValley_EventScript_Lucia_Text_1
	msgbox RocarohaValley_EventScript_Lucia_Text_2
	release
	end


RocarohaValley_EventScript_Alvaro::
	trainerbattle_single TRAINER_G2_ALVARO, RocarohaValley_EventScript_Lucia_Text_0, RocarohaValley_EventScript_Lucia_Text_1
	msgbox RocarohaValley_EventScript_Lucia_Text_2
	release
	end


RocarohaValley_EventScript_Belen::
	trainerbattle_single TRAINER_G2_BELEN, RocarohaValley_EventScript_Lucia_Text_0, RocarohaValley_EventScript_Lucia_Text_1
	msgbox RocarohaValley_EventScript_Lucia_Text_2
	release
	end


RocarohaValley_EventScript_Mari::
	trainerbattle_double TRAINER_G2_MARI_AND_NOEL, RocarohaValley_EventScript_Lucia_Text_0, RocarohaValley_EventScript_Lucia_Text_1, RocarohaValley_EventScript_Mari_Text_0
	msgbox RocarohaValley_EventScript_Lucia_Text_2
	release
	end


RocarohaValley_EventScript_Noel::
	trainerbattle_double TRAINER_G2_MARI_AND_NOEL, RocarohaValley_EventScript_Lucia_Text_0, RocarohaValley_EventScript_Lucia_Text_1, RocarohaValley_EventScript_Mari_Text_0
	msgbox RocarohaValley_EventScript_Lucia_Text_2
	release
	end


RocarohaValley_EventScript_Milton::
	trainerbattle_single TRAINER_G2_MILTON, RocarohaValley_EventScript_Lucia_Text_0, RocarohaValley_EventScript_Lucia_Text_1
	msgbox RocarohaValley_EventScript_Lucia_Text_2
	release
	end


RocarohaValley_EventScript_Lionel::
	trainerbattle_single TRAINER_G2_LIONEL, RocarohaValley_EventScript_Lucia_Text_0, RocarohaValley_EventScript_Lucia_Text_1
	msgbox RocarohaValley_EventScript_Lucia_Text_2
	release
	end


RocarohaValley_EventScript_Santi_Text_0:
	.string "I'm a fish out of water!$"

RocarohaValley_EventScript_Santi_Text_1:
	.string "All I could do was flop!$"

RocarohaValley_EventScript_Santi_Text_2:
	.string "Y'know, lately I've been leaping\noff the cliffs at the Land Bridge.\pIt's great fun, I tell you!$"

RocarohaValley_EventScript_Lucia_Text_0:
	.string "Battle me now!$"

RocarohaValley_EventScript_Lucia_Text_1:
	.string "No, I lost!$"

RocarohaValley_EventScript_Lucia_Text_2:
	.string "You're good.$"

RocarohaValley_EventScript_Mari_Text_0:
	.string "We only battle folks with\ntwo Pokémon!$"
