LandBridgeNorth_MapScripts::
	.byte 0


LandBridgeNorth_EventScript_Ala::
	trainerbattle_single TRAINER_G2_ALA, LandBridgeNorth_EventScript_Ala_Text_0, LandBridgeNorth_EventScript_Ala_Text_1
	msgbox LandBridgeNorth_EventScript_Ala_Text_2
	release
	end


LandBridgeNorth_EventScript_Shanti::
	trainerbattle_single TRAINER_G2_SHANTI, LandBridgeNorth_EventScript_Shanti_Text_0, LandBridgeNorth_EventScript_Shanti_Text_1
	msgbox LandBridgeNorth_EventScript_Shanti_Text_2
	release
	end


LandBridgeNorth_EventScript_Cesar::
	trainerbattle_single TRAINER_G2_CESAR, LandBridgeNorth_EventScript_Cesar_Text_0, LandBridgeNorth_EventScript_Cesar_Text_1
	msgbox LandBridgeNorth_EventScript_Cesar_Text_2
	release
	end


LandBridgeNorth_EventScript_Guillermo::
	trainerbattle_single TRAINER_G2_GUILLERMO, LandBridgeNorth_EventScript_Guillermo_Text_0, LandBridgeNorth_EventScript_Guillermo_Text_1
	msgbox LandBridgeNorth_EventScript_Guillermo_Text_2
	release
	end


LandBridgeNorth_EventScript_Valentin::
	trainerbattle_single TRAINER_G2_VALENTIN, LandBridgeNorth_EventScript_Valentin_Text_0, LandBridgeNorth_EventScript_Valentin_Text_1
	msgbox LandBridgeNorth_EventScript_Valentin_Text_2
	release
	end


LandBridgeNorth_EventScript_Torie::
	trainerbattle_single TRAINER_G2_TORIE, LandBridgeNorth_EventScript_Torie_Text_0, LandBridgeNorth_EventScript_Torie_Text_1
	msgbox LandBridgeNorth_EventScript_Torie_Text_2
	release
	end


LandBridgeNorth_EventScript_Jorge::
	trainerbattle_single TRAINER_G2_JORGE, LandBridgeNorth_EventScript_Jorge_Text_0, LandBridgeNorth_EventScript_Jorge_Text_1
	msgbox LandBridgeNorth_EventScript_Jorge_Text_2
	release
	end


LandBridgeNorth_EventScript_Agustin::
	trainerbattle_single TRAINER_G2_AGUSTIN, LandBridgeNorth_EventScript_Agustin_Text_0, LandBridgeNorth_EventScript_Agustin_Text_1
	msgbox LandBridgeNorth_EventScript_Agustin_Text_2
	release
	end


LandBridgeNorth_EventScript_Ala_Text_0:
	.string "This is a warm-up for when I\nclimb Wing Peak!$"

LandBridgeNorth_EventScript_Ala_Text_1:
	.string "I'm all sweaty now…$"

LandBridgeNorth_EventScript_Ala_Text_2:
	.string "I think I should train a\nlittle more before I climb\lWing Peak.$"

LandBridgeNorth_EventScript_Shanti_Text_0:
	.string "My Pokémon has fists of iron!\nI won't lose!$"

LandBridgeNorth_EventScript_Shanti_Text_1:
	.string "My Pokémon has fists of iron, but\nyours has fists of steel!$"

LandBridgeNorth_EventScript_Shanti_Text_2:
	.string "I guess fist strength doesn't make a\ndifference if you skip leg day…$"

LandBridgeNorth_EventScript_Cesar_Text_0:
	.string "Together with my Pokémon, a beautiful\norchestra is created!$"

LandBridgeNorth_EventScript_Cesar_Text_1:
	.string "The choir softly weeps…$"

LandBridgeNorth_EventScript_Cesar_Text_2:
	.string "My dream is to compose a soundtrack\nfor the Pokémon Musical in Unova.$"

LandBridgeNorth_EventScript_Guillermo_Text_0:
	.string "Instead of a Pokémon, I've reeled\nin a Trainer!\pThis is a massive catch!$"

LandBridgeNorth_EventScript_Guillermo_Text_1:
	.string "Sunk the line!$"

LandBridgeNorth_EventScript_Guillermo_Text_2:
	.string "Fishing requires patience, just like\nraising Pokémon.\pIn that regard, fishing and battling\nare quite similar.$"

LandBridgeNorth_EventScript_Valentin_Text_0:
	.string "…Flippin' fish sticks!\nYou made me lose my catch!$"

LandBridgeNorth_EventScript_Valentin_Text_1:
	.string "And you defeated my precious\nPokémon too?\lJust go!$"

LandBridgeNorth_EventScript_Valentin_Text_2:
	.string "I should've known better than to\nfish in a spot like this…\pTrainers keep challenging me left and\nright!$"

LandBridgeNorth_EventScript_Torie_Text_0:
	.string "My Floatzel's water sac is just\nlike my inflatable tube!$"

LandBridgeNorth_EventScript_Torie_Text_1:
	.string "Floatzel!\nNo!$"

LandBridgeNorth_EventScript_Torie_Text_2:
	.string "Since my Floatzel evolved from a\nBuizel, I always lose in a swimming\nrace.$"

LandBridgeNorth_EventScript_Jorge_Text_0:
	.string "My Pokémon are rare and refined.\nThey won't lose to a commoner like you.$"

LandBridgeNorth_EventScript_Jorge_Text_1:
	.string "Ugh…\nSo unruly…$"

LandBridgeNorth_EventScript_Jorge_Text_2:
	.string "You ought to learn some manners.$"

LandBridgeNorth_EventScript_Agustin_Text_0:
	.string "Oh, a Trainer!\nWhaddaya say we have a scrap?$"

LandBridgeNorth_EventScript_Agustin_Text_1:
	.string "Me and my big mouth…$"

LandBridgeNorth_EventScript_Agustin_Text_2:
	.string "Sometimes it's not a good idea to\nbattle every Trainer you see…$"
