LandBridgeNorth_MapScripts::
	.byte 0


LandBridgeNorth_EventScript_Ala::
	trainerbattle_single TRAINER_G2_ALA, LandBridgeNorth_EventScript_Ala_Text_0, LandBridgeNorth_EventScript_Ala_Text_1
	msgbox LandBridgeNorth_EventScript_Ala_Text_2
	release
	end


LandBridgeNorth_EventScript_Shanti::
	trainerbattle_single TRAINER_G2_SHANTI, LandBridgeNorth_EventScript_Ala_Text_0, LandBridgeNorth_EventScript_Ala_Text_1
	msgbox LandBridgeNorth_EventScript_Ala_Text_2
	release
	end


LandBridgeNorth_EventScript_Cesar::
	trainerbattle_single TRAINER_G2_CESAR, LandBridgeNorth_EventScript_Ala_Text_0, LandBridgeNorth_EventScript_Ala_Text_1
	msgbox LandBridgeNorth_EventScript_Ala_Text_2
	release
	end


LandBridgeNorth_EventScript_Guillermo::
	trainerbattle_single TRAINER_G2_GUILLERMO, LandBridgeNorth_EventScript_Ala_Text_0, LandBridgeNorth_EventScript_Ala_Text_1
	msgbox LandBridgeNorth_EventScript_Ala_Text_2
	release
	end


LandBridgeNorth_EventScript_Valentin::
	trainerbattle_single TRAINER_G2_VALENTIN, LandBridgeNorth_EventScript_Ala_Text_0, LandBridgeNorth_EventScript_Ala_Text_1
	msgbox LandBridgeNorth_EventScript_Ala_Text_2
	release
	end


LandBridgeNorth_EventScript_Torie::
	trainerbattle_single TRAINER_G2_TORIE, LandBridgeNorth_EventScript_Ala_Text_0, LandBridgeNorth_EventScript_Ala_Text_1
	msgbox LandBridgeNorth_EventScript_Ala_Text_2
	release
	end


LandBridgeNorth_EventScript_Jorge::
	trainerbattle_single TRAINER_G2_JORGE, LandBridgeNorth_EventScript_Ala_Text_0, LandBridgeNorth_EventScript_Ala_Text_1
	msgbox LandBridgeNorth_EventScript_Ala_Text_2
	release
	end


LandBridgeNorth_EventScript_Agustin::
	trainerbattle_single TRAINER_G2_AGUSTIN, LandBridgeNorth_EventScript_Ala_Text_0, LandBridgeNorth_EventScript_Ala_Text_1
	msgbox LandBridgeNorth_EventScript_Ala_Text_2
	release
	end


LandBridgeNorth_EventScript_Ala_Text_0:
	.string "Battle me now!$"

LandBridgeNorth_EventScript_Ala_Text_1:
	.string "No, I lost!$"

LandBridgeNorth_EventScript_Ala_Text_2:
	.string "You're good.$"
