@ Color Ruins text

ColorRuinsRed_1F_Text_GiveChase:
	.string "SUMMON THE STATUE AND GIVE CHASE.$"

ColorRuinsRed_1F_Text_KeepToRight:
	.string "KEEPING TO THE RIGHT IS THE KEY.$"

ColorRuinsRed_1F_Text_StrongOpponents:
	.string "STRONG OPPONENTS GIVE GREAT REWARDS.$"

ColorRuinsRed_1F_Text_RighteousPath:
	.string "I WANT TO WALK A RIGHTEOUS PATH.$"

ColorRuinsRed_1F_Text_CheapRice:
	.string "CHEAP RICE TODAY ONLY$"

ColorRuinsYellow_1F_Text_TouchPillars:
	.string "TOUCH PILLARS FROM RIGHT TO LEFT.$"

ColorRuinsYellow_1F_Text_SacredStones:
	.string "SACRED STONES LIE BENEATH GOLD.$"

ColorRuinsYellow_1F_Text_MazhouTei:
	.string "MAZHOU X TEI. TOGETHER IN HARMONY.$"

ColorRuinsYellow_1F_Text_GoldenCups:
	.string "GOLDEN CUPS. MANY YUAN$"

ColorRuinsYellow_1F_Text_VermillionBird:
	.string "I SAW A VERMILLION BIRD IN EAST.$"

ColorRuinsYellow_1F_Text_TalkingToPeople:
	.string "I AM NOT GOOD AT TALKING TO PEOPLE.$"

ColorRuinsYellow_1F_Text_CurseTheEmperor:
	.string "CURSE THE EMPEROR. HE IS A FRAUD.$"

ColorRuinsYellow_1F_Text_PurpleTrees:
	.string "STAY AWAY FROM PURPLE TALKING TREES.$"

ColorRuinsGreen_1F_Text_TouchCorners:
	.string "TOUCH THE CORNERS COUNTERCLOCKWISE.$"

ColorRuinsGreen_1F_Text_BallsFromNuggets:
	.string "CAN YOU MAKE BALLS FROM NUGGETS$"

ColorRuinsGreen_1F_Text_CarnivineBest:
	.string "CARNIVINE IS SURELY THE BEST.$"

ColorRuinsGreen_1F_Text_MushroomsDust:
	.string "GRIND MUSHROOMS INTO MEDICINAL DUST.$"

ColorRuinsGreen_1F_Text_QinqinWasHere:
	.string "QINQIN WAS HERE$"

ColorRuinsGreen_1F_Text_SunStoneEvolved:
	.string "IT TOUCHED A SUN STONE AND EVOLVED.$"

ColorRuinsGreen_1F_Text_UniteTheCountry:
	.string "I WANT TO UNITE THE COUNTRY.$"

ColorRuinsGreen_1F_Text_SwimmingInTheMarsh:
	.string "SWIMMING IN THE MARSH IS GREAT$"

ColorRuinsGreen_1F_Text_AnotherColorRuins:
	.string "I AM WORKING ON ANOTHER COLOR RUINS$"

ColorRuinsGreen_1F_Text_PureHearts:
	.string "PURE HEARTS WILL GO FAR.$"

ColorRuinsGreen_1F_Text_MoneyIsNotAll:
	.string "MONEY IS NOT ALL THAT MATTERS.$"

ColorRuinsBlue_1F_Text_TouchedWall:
	.string "{PLAYER} touched the wall…$"

ColorRuinsBlue_1F_Text_NothingHappened:
	.string "But nothing happened.$"

ColorRuinsBlue_1F_Text_TriggerRain:
	.string "FIND THE WALL AND TRIGGER THE RAIN$"

ColorRuinsBlue_1F_Text_TiredMinds:
	.string "TIRED MINDS THINK HARD$"

ColorRuinsBlue_1F_Text_WhitePearls:
	.string "HE SAID WHITE PEARLS LIE IN RIVERS$"

ColorRuinsBlue_1F_Text_HotSpring:
	.string "THERE IS A HOT SPRING NEAR HERE$"

ColorRuinsBlue_1F_Text_BambooCrop:
	.string "MY BAMBOO CROP HAS BEEN BURNT DOWN$"

ColorRuinsBlue_1F_Text_ShadowsDance:
	.string "SHADOWS DANCE IN THE SKY$"

ColorRuinsBlue_1F_Text_PerfectPetals:
	.string "PERFECT PETALS ARE HARD TO COME BY$"

ColorRuinsYellow_B1F_Text_LotsOfWriting:
	.string "This wall is filled with writing…\n"
	.string "Would you like to read it?$"

ColorRuinsYellow_B1F_Text_ColorRuinsHistory:
	.string "WE CARVED THESE CAVES INTO RUINS.\n"
	.string "IT TOOK MANY YEARS.\p"
	.string "BLOOD, SWEAT AND TEARS WERE SHED\n"
	.string "DURING THE CREATION OF THIS PLACE.\p"
	.string "THE PURPOSE OF THESE COLOR RUINS\n"
	.string "IS TO STORE INFORMATION FOR\l"
	.string "OURSELVES AND OUR CHILDREN.\p"
	.string "IMPORTANT EVENTS ARE ETERNALLY\n"
	.string "ETCHED INTO HARD STONE.\p"
	.string "FROM BIRTH RECORDS TO RANDOM\n"
	.string "MUSINGS, REMEMBERANCE IS VITAL.$"

ColorRuinsGreen_B1F_Text_RumorOfAttack:
	.string "SOMEBODY HEARD THAT PILLAGERS WERE\n"
	.string "GOING TO ATTACK OUR DEAR VILLAGE.\p"
	.string "THESE PILLAGERS WERE DANGEROUS,\n"
	.string "PEOPLE WHO WISHED TO TAKE OVER ALL.\p"
	.string "PROTECTING OUR LIVES AND VALUABLE\n"
	.string "ITEMS WAS OF UTMOST IMPORTANCE.\p"
	.string "THE COLOR RUINS WERE SEALED SO\n"
	.string "THAT WE WOULD NOT BE COMPROMISED.$"

ColorRuinsGreen_B1F_Text_EssenceOfSun:
	.string "EXPOSURE TO THE ESSENCE OF THE SUN\n"
	.string "MAY RESULT IN SUDDEN EVOLUTION$"

ColorRuinsGreen_B1F_Text_EssenceOfWater:
	.string "EXPOSURE TO THE ESSENCE OF WATER\n"
	.string "MAY RESULT IN SUDDEN EVOLUTION$"

ColorRuinsGreen_B1F_Text_EssenceOfWoods:
	.string "EXPOSURE TO THE ESSENCE OF THE\n"
	.string "WOODS MAY RESULT IN SUDDEN EVOLUTION$"

ColorRuinsRed_B1F_Text_SealingTheRuins:
	.string "WE SEALED ALL FOUR COLOR RUINS\n"
	.string "TO DENY ACCESS TO PILLAGERS.\p"
	.string "A UNIQUE LOCK WAS GIVEN TO EACH.\p"
	.string "WE WROTE INSTRUCTIONS ON UNSEALING\n"
	.string "THE RUINS IN OUR MOTHER TONGUE.\p"
	.string "FOR THE PILLAGERS, OUR DIALECT WAS\n"
	.string "UNKNOWN, THEY COULD NOT READ OUR\l"
	.string "INSCRIPTIONS, SO ACCESS WAS DENIED.\p"
	.string "WE FLED ONCE THE RUINS WERE SEALED.$"

ColorRuinsBlue_B1F_Text_AfterTheAttack:
	.string "AFTER THE ATTACK SOME OF US\n"
	.string "RETURNED TO OUR FORMER HOMES.\p"
	.string "IT WAS OUR LUCK THAT THE\n"
	.string "PILLAGERS HAD NOT SETTLED.\p"
	.string "EVERYTHING WAS INTACT\n"
	.string "OUR PLAN HAD WORKED.\p"
	.string "WE THEN BEGAN -\p"
	.string "The rest of the wall is damaged\n"
	.string "to a point of being unreadable.$"


