@ story text

JamKeyMap_Text_Mechanic:
	.string "{JPN}うーん…\n"
	.string "{JPN}これは　むずかしいな…$"

JamKeyMap_Text_MechanicHey:
	.string "{JPN}おーい, {PLAYER}！\n"
	.string "{JPN}ここに　きて！$"

JamKeyMap_Text_GoodAsNew:
	.string "{JPN}ふたたび　エンジンが　うごいている！\p"
	.string "{JPN}ふたたび　はたらかせることが\n"
	.string "{JPN}できることを　しっていった。\p"
	.string "{JPN}It did take a while, I had to mess\n"
	.string "{JPN}with the exhaust a little bit and\l"
	.string "{JPN}replace the battery, but here she is!\p"
	.string "{JPN}You just come find me if you ever\n"
	.string "{JPN}need any more help!$"

JamKeyMap_Text_CantLeave:
	.string "{JPN}がいしゅつしない！\n"
	.string "{JPN}トラックに　のるが　ひつよう$"

JamKeyMap_Text_TruckWontStart:
	.string "{JPN}エンジンが　まわせない\n"
	.string "{JPN}トラックが　こわれた！$"

JamKeyMap_Text_PulpUrgh:
	.string "{JPN}エンジンが　まわせない\p"
	.string "{JPN}にしの　チョむらまで\n"
	.string "{JPN}あるいていくが　ひつよう…$"

JamKeyMap_Text_LogPleaseBattleMe:
	.string "{JPN}Oh, it's {PLAYER}!\n"
	.string "{JPN}How's it going?\p"
	.string "{JPN}W-whaat?!\n"
	.string "{JPN}You actually found that relic?!\l"
	.string "{JPN}T-that's incredible!\p"
	.string "{JPN}So, I guess you're… going?\p"
	.string "{JPN}Before you go, {PLAYER}…\n"
	.string "{JPN}Let's have another battle.\p"
	.string "{JPN}But this time, I'll win!\p"
	.string "{JPN}I'll let you prepare, so talk\n"
	.string "{JPN}to me when you're ready to fight.$"

JamKeyMap_Text_LogIntro:
	.string "{JPN}Well then, {PLAYER}!\n"
	.string "{JPN}Our final fight… here I come!$"

JamKeyMap_Text_LogDefeat:
	.string "{JPN}Aha, nothing's changed!$"

JamKeyMap_Text_LogPostBattle:
	.string "{JPN}Like always, you win…\n"
	.string "{JPN}But I don't care!\p"
	.string "{JPN}I just like to battle, whether\n"
	.string "{JPN}I win or lose!\p"
	.string "{JPN}My Pokémon feel the same way.\p"
	.string "{JPN}So, looks like this is goodbye…\n"
	.string "{JPN}I'm not jealous or anything.\p"
	.string "{JPN}I can find meaning in my construction\n"
	.string "{JPN}work, so I'm happy right here!\p"
	.string "{JPN}Yup, so go ahead and enjoy yourself\n"
	.string "{JPN}in big ol' Honzhu City!\n"
	.string "{JPN}Make sure you work hard on the\n"
	.string "{JPN}Berry business too, though!\p"
	.string "{JPN}And send me a postcard when you\n"
	.string "{JPN}get there!\p"
	.string "{JPN}Well, old friend…\n"
	.string "{JPN}Farewell!$"

FarmerField_Text_MyNameIsPulp:
	.string "{JPN}おいらの　なまえは　パルプだ。$"

FarmerField_Text_RuralFarmer:
	.string "{JPN}I'm a farmer in a rural, poor\n"
	.string "{JPN}area in the middle of nowhere.$"

FarmerField_Text_BerryFarmer:
	.string "{JPN}Specifically, I'm a Berry farmer.$"

FarmerField_Text_EveryoneHasAJob:
	.string "{JPN}Everyone here has a job, and mine\n"
	.string "{JPN}is to grow Berries and sell them.$"

FarmerField_Text_LifeIsTough:
	.string "{JPN}Life is tough here.\n"
	.string "{JPN}All of us have to work hard to survive.$"

FarmerField_Text_GoWithoutFood:
	.string "{JPN}If you can't work, then you can't make\n"
	.string "{JPN}money, and you have to go without food.$"

FarmerField_Text_HaveADream:
	.string "{JPN}But I have a dream!$"

FarmerField_Text_DontKnowHow:
	.string "{JPN}I don't know how to achieve it, but…$"

FarmerField_Text_WantToGetAway:
	.string "{JPN}I want to escape this rural lifestyle.\p"
	.string "{JPN}I want to grow Berries on a\n"
	.string "{JPN}wider scale.$"

FarmerField_Text_WantToMoveCity:
	.string "{JPN}I want to move to Honzhu City,\n"
	.string "{JPN}a gigantic city in the south!$"

FarmerField_Text_CityIsAmazing:
	.string "{JPN}Honzhu City is amazing.\p"
	.string "{JPN}It's a bustling metropolis with\n"
	.string "{JPN}opportunities to do all kinds of things.\p"
	.string "{JPN}It's a very rich city full of\n"
	.string "{JPN}all kinds of people.\p"
	.string "{JPN}My late father told me stories of\n"
	.string "{JPN}Honzhu, as he got to visit once\l"
	.string "{JPN}when he was a young man.\p"
	.string "{JPN}And since then, it's been my dream\n"
	.string "{JPN}to escape this place and move there.$"

FarmerField_Text_AllDone:
	.string "{JPN}…All done!\p"
	.string "{JPN}Finally, I managed to pick all the\n"
	.string "{JPN}Berries for the mechanic's order.\p"
	.string "{JPN}Now to get in the truck and deliver\n"
	.string "{JPN}it to him!$"

ShendownPath_Text_Sign:
	.string "{JPN}Shendown Path$"

ShendownPath_Text_Fisherman:
	.string "{JPN}Pokémon battle?\p"
	.string "{JPN}{PLAYER}, you know I'm not\n"
	.string "{JPN}into that stuff at all!\p"
	.string "{JPN}No, all I want to do is fish!\n"
	.string "{JPN}All day and all night!\p"
	.string "{JPN}You should give up farming and\n"
	.string "{JPN}come be a fisherman with me!$"

ChoVillage_Text_InnSign:
	.string "{JPN}Cho Village Inn$"

ChoVillage_Text_Man:
	.string "{JPN}Hey there, {PLAYER}!$"

ChoVillage_Text_Woman:
	.string "{JPN}Good day, {PLAYER}.\n"
	.string "{JPN}I heard the Berry harvest this year\l"
	.string "{JPN}is going well. Good for you!$"

ChoVillage_Text_ComplainingFisherman:
	.string "{JPN}Argh, I can't catch any fish at all!\p"
	.string "{JPN}It must be because of all those\n"
	.string "{JPN}Grimer polluting the river!$"

ChoVillage_Text_EarlyLogIntro:
	.string "{JPN}Yo, it's {PLAYER}!\n"
	.string "{JPN}How's it going, old friend?\l"
	.string "{JPN}I just got back from work!\p"
	.string "{JPN}Of course, now that our eyes have\n"
	.string "{JPN}met, we've got to have a battle, right?!$"

ChoVillage_Text_EarlyLogDefeat:
	.string "{JPN}No way, that was a fluke!$"

ChoVillage_Text_EarlyLogPostBattle:
	.string "{JPN}I thought I was going to win\n"
	.string "{JPN}this time for sure…\p"
	.string "{JPN}Anyway, how come you're not driving\n"
	.string "{JPN}here in the truck today?\p"
	.string "{JPN}Huh? It's broken down?\p"
	.string "{JPN}Looks like you'd better go see the\n"
	.string "{JPN}mechanic. He lives in the north-west\l"
	.string "{JPN}of the village.\p"
	.string "{JPN}If anyone can fix your truck, it'll\n"
	.string "{JPN}be that guy.\p"
	.string "{JPN}By the way, I was thinking about\n"
	.string "{JPN}what you told me the other day.\p"
	.string "{JPN}You said you wanted to move to the\n"
	.string "{JPN}city, and I was all for it, but…\p"
	.string "{JPN}Now that I think about it, moving\n"
	.string "{JPN}to the city requires so much money,\l"
	.string "{JPN}more money than we'd make in a decade…\p"
	.string "{JPN}Oh, I have an idea.\n"
	.string "{JPN}You should go and see the Oracle.\p"
	.string "{JPN}He might have an idea on how you could\n"
	.string "{JPN}get enough money to move to the city.\p"
	.string "{JPN}Anyhow, I've got to go!\p"
	.string "{JPN}Can't spend too much time dawdling,\n"
	.string "{JPN}because time is money! See ya!$"

ChoVillage_Text_LogIntro:
	.string "{JPN}Yo, {PLAYER}!\n"
	.string "{JPN}Fancy seeing you again so soon!\p"
	.string "{JPN}So, did you speak to the Oracle?$"

ChoVillage_Text_LogNext:
	.string "{JPN}You did?\n"
	.string "{JPN}And now you're investigating the\l"
	.string "{JPN}Color Ruins? Sounds fun!\p"
	.string "{JPN}But if you're planning to go to all of\n"
	.string "{JPN}the Color Ruins, you're out of luck!\p"
	.string "{JPN}You can't get to the red Color Ruins on\n"
	.string "{JPN}foot because the river is in the way!\p"
	.string "{JPN}Luckily for you, your best friend, me,\n"
	.string "{JPN}specializes in building bridges!\p"
	.string "{JPN}Yup, your dreams are my dreams, buddy,\n"
	.string "{JPN}so I'll go and build a bridge to the\l"
	.string "{JPN}red Color Ruins on Shendown Path.\l"
	.string "{JPN}It might take a little while though!\p"
	.string "{JPN}I've got yet another job to get to, so\n"
	.string "{JPN}I'll speak to you again later! See ya!$"

ChoVillage_Text_WantMorePeopleFish:
	.string "{JPN}I want more young people to fish.\n"
	.string "{JPN}Do you want to learn to fish?$"

ChoVillage_Text_MyOldFishingRod:
	.string "{JPN}Very good!\n"
	.string "{JPN}Here, take my old fishing rod.$"

ChoVillage_Text_FishingMaySeemDifficult:
	.string "{JPN}Now, fishing may seem difficult,\n"
	.string "{JPN}but it's actually very simple.\p"
	.string "{JPN}First, you want to face the water,\n"
	.string "{JPN}then use the rod.\p"
	.string "{JPN}Focus your mind…\n"
	.string "{JPN}If you get a bite, pull on the rod.\p"
	.string "{JPN}Sometimes you can snag something\n"
	.string "{JPN}immediately, but with bigger catches,\l"
	.string "{JPN}you need to time the pulls on your rod\l"
	.string "{JPN}to haul them in.$"

ChoVillage_Text_ThatsTooBadThen:
	.string "{JPN}Oh, is that so?\n"
	.string "{JPN}That's too bad, then.$"

ChoVillage_Text_HowsYourFishing:
	.string "{JPN}Yo!\n"
	.string "{JPN}How's your fishing?$"

ChoVillage_Text_GreatHaulInSomeBigOnes:
	.string "{JPN}Is that right! That's great!\n"
	.string "{JPN}Haul in some big ones!$"

ChoVillage_Text_TimingYourPulls:
	.string "{JPN}Remember, timing your pulls\n"
	.string "{JPN}is key when it comes to fishing.$"

WangyongMarsh_Text_ThinkingMan:
	.string "{JPN}Our Cho Village is just a tiny,\n"
	.string "{JPN}isolated part of a huge region…\p"
	.string "{JPN}There's still a lot of things\n"
	.string "{JPN}we have no idea about.\p"
	.string "{JPN}I wonder what else the world holds.$"

KimyangRoad_Text_ItemfinderIntro:
	.string "{JPN}Are you looking for items\n"
	.string "{JPN}hidden around the field?\p"
	.string "{JPN}Then take this!$"

KimyangRoad_Text_ItemfinderExplain:
	.string "{JPN}That's an Itemfinder.\n"
	.string "{JPN}I got it when I took a trip\l"
	.string "{JPN}to Honzhu City in the south.\p"
	.string "{JPN}It reacts when hidden items are\n"
	.string "{JPN}detected, so it's really useful.$"

KimyangRoad_Text_ItemfinderRecieved:
	.string "{JPN}There are items hidden everywhere.\n"
	.string "{JPN}You should use the Itemfinder often!$"

OracleHill_Text_OldWoman:
	.string "{JPN}Fu fu fu fu…\p"
	.string "{JPN}This path leads to the Oracle's cave.\p"
	.string "{JPN}But I'm sure you knew that, didn't you?$"

OracleHill_Text_CaveRoadblock:
	.string "{JPN}I'm sorry, but the Oracle is at\n"
	.string "{JPN}a ceremony right now…\p"
	.string "{JPN}He will be back shortly, but surely\n"
	.string "{JPN}you have errands to run in the\l"
	.string "{JPN}meantime, hmm?$"

ZhaounPath_Text_NoTallGrass:
	.string "{JPN}There isn't much tall grass here…\n"
	.string "{JPN}Did somebody cut it all down?$"

DarkCityEntrance_Text_ArumStrangeSound:
	.string "{JPN}I heard a strange sound, so I came.\n"
	.string "{JPN}And look what I've found!\p"
	.string "{JPN}Where did you come from, son?\p"
	.string "{JPN}Oh? You fell through the floor in\n"
	.string "{JPN}the blue Color Ruins? I see…\p"
	.string "{JPN}My name is Arum.\n"
	.string "{JPN}And this is the Dark City!$"

DarkCityEntrance_Text_ArumExplain:
	.string "{JPN}Hm? You look confused.\n"
	.string "{JPN}Let me explain a little more.\p"
	.string "{JPN}Many decades ago, our ancestors\n"
	.string "{JPN}wanted to build a successor to\l"
	.string "{JPN}the Color Ruins deep underground.\p"
	.string "{JPN}At the time, there was lots of\n"
	.string "{JPN}political tension on the surface,\l"
	.string "{JPN}and everyone was on edge.\p"
	.string "{JPN}So our ancestors decided to not\n"
	.string "{JPN}just build a Ruins underground, but\l"
	.string "{JPN}to build an entire civilisation!\p"
	.string "{JPN}We're rather isolated from the\n"
	.string "{JPN}rest of the world down here.\p"
	.string "{JPN}However, we do have our ways of\n"
	.string "{JPN}getting back to the surface.\p"
	.string "{JPN}Anyway, you said you fell through\n"
	.string "{JPN}the blue Color Ruins, right?\l"
	.string "{JPN}Why on earth were you in there?$"

DarkCityEntrance_Text_ArumRelic:
	.string "{JPN}Searching for a golden relic, huh?\n"
	.string "{JPN}Well, you got lucky, son!\l"
	.string "{JPN}That old legend is true!\p"
	.string "{JPN}The Relic Crown has been passed from\n"
	.string "{JPN}person to person for many centuries.\p"
	.string "{JPN}I am its current owner!\p"
	.string "{JPN}If you want to know more, then follow\n"
	.string "{JPN}me to the Dark City's main chamber!$"

DarkCityMain_Text_HotSpringInfo:
	.string "{JPN}This hot spring has healing properties.\p"
	.string "{JPN}If you take a dip in it, then your\n"
	.string "{JPN}Pokémon team's health will be restored.$"

DarkCityMain_Text_CaveLover:
	.string "{JPN}I was born and raised in Dark City,\n"
	.string "{JPN}but I occasionally explore the surface.\p"
	.string "{JPN}However, as a lover of caves, this\n"
	.string "{JPN}is a perfect place for me to live.$"

DarkCityMain_Text_MoneyRare:
	.string "{JPN}We don't use money much in this city.\n"
	.string "{JPN}Most of the time, we barter goods.$"

DarkCityMain_Text_WomanBathingInSpring:
	.string "{JPN}Ah… that hits the spot…$"

DarkCityMain_Text_ShopSign:
	.string "{JPN}DARK CITY GENERAL STORE\n"
	.string "{JPN}NOW ACCEPTING SURFACE CURRENCY$"

DarkCityMain_Text_PokemonHealed:
	.string "{JPN}Your Pokémon were restored to full\n"
	.string "{JPN}health!$"

DarkCityMain_Text_ArumSoCool:
	.string "{JPN}Arum is so cool…\n"
	.string "{JPN}He's the strongest Trainer ever!$"

DarkCityMain_Text_RelicCrownInfo:
	.string "{JPN}My Relic Crown is indeed the golden\n"
	.string "{JPN}relic from that ancient story.\p"
	.string "{JPN}I found it five years ago on an\n"
	.string "{JPN}excursion I took to a mountain in\l"
	.string "{JPN}the east.\p"
	.string "{JPN}You want the Crown, don't you?\n"
	.string "{JPN}I can see it in your eyes…\p"
	.string "{JPN}For years, people have been trying\n"
	.string "{JPN}to buy the Relic Crown off of me.\p"
	.string "{JPN}But I will not sell out so easily!\n"
	.string "{JPN}Money is of no concern to me, anyway.\p"
	.string "{JPN}No, what I care about is puzzles!\p"
	.string "{JPN}Do you remember the puzzles you had\n"
	.string "{JPN}to solve in order to explore the\l"
	.string "{JPN}back caves of the Color Ruins?\p"
	.string "{JPN}I created many puzzles just like\n"
	.string "{JPN}them and filled the Dark Ruins behind\l"
	.string "{JPN}me with them.\p"
	.string "{JPN}If you want the Relic Crown, you must\n"
	.string "{JPN}solve all of these puzzles!\p"
	.string "{JPN}Follow me, uh…$"

DarkCityMain_Text_ForgotToAskName:
	.string "{JPN}Oh, so sorry!\n"
	.string "{JPN}I didn't even ask your name!$"

DarkCityMain_Text_PulpIsIt:
	.string "{JPN}{PLAYER}, is it?\n"
	.string "{JPN}Follow me!$"

DarkRuins_Text_ArumExplanation:
	.string "{JPN}Welcome to the Dark Ruins!\p"
	.string "{JPN}Each room in here has a puzzle\n"
	.string "{JPN}expertly crafted by yours truly!\p"
	.string "{JPN}If you can solve all four puzzles,\n"
	.string "{JPN}the Relic Crown will be your reward.\p"
	.string "{JPN}Nobody has ever been able to solve\n"
	.string "{JPN}all four of my puzzles, so you have\l"
	.string "{JPN}quite the challenge ahead of you!$"

DarkRuins_Text_ArumWaitAtEnd:
	.string "{JPN}I'll be waiting inside this room,\n"
	.string "{JPN}which will close once I step inside.\p"
	.string "{JPN}It will reopen once you've solved\n"
	.string "{JPN}all four puzzles.\p"
	.string "{JPN}Good luck, {PLAYER}…$"

LinkingTunnel_Text_DiglettAsleep:
	.string "{JPN}The Diglett is sleeping soundly.$"

LinkingTunnel_Text_DiglettBlockingWay:
	.string "{JPN}I wanted to get to Zhaoun Path, but\n"
	.string "{JPN}these Diglett are blocking the way!\p"
	.string "{JPN}I'm sure they'll wake up and move\n"
	.string "{JPN}soon enough, though.$"

ChoVillage_House5_Text_WhatIsStrength:
	.string "{JPN}What is strength?\p"
	.string "{JPN}Obviously, it's the ability\n"
	.string "{JPN}to clear obstacles in your way!\p"
	.string "{JPN}Have you ever noticed rugged\n"
	.string "{JPN}rocks in the field?\p"
	.string "{JPN}I'll teach you how to smash those\n"
	.string "{JPN}rocks if you tell me what lies inside\l"
	.string "{JPN}the yellow Color Ruins!\p"
	.string "{JPN}Please!\n"
	.string "{JPN}I've always wanted to know!$"

ChoVillage_House5_Text_TellAboutRuins:
	.string "{JPN}What?!\p"
	.string "{JPN}There's a secret cave behind the\n"
	.string "{JPN}walls of the yellow Color Ruins?!\p"
	.string "{JPN}I thought that there would totally\n"
	.string "{JPN}be a pot of gold or something!\p"
	.string "{JPN}Well, whatever.\n"
	.string "{JPN}You came to learn how to smash rocks,\l"
	.string "{JPN}so I'll teach you the art of Rock Smash!$"

ChoVillage_House5_Text_RockSmashTutorial:
	.string "{JPN}Rock Smash is actually pretty simple.\p"
	.string "{JPN}Tense your muscles, and then…$"

ChoVillage_House5_Text_Wacha:
	.string "{JPN}Wachaaaa!$"

ChoVillage_House5_Text_SeePrettyEasy:
	.string "{JPN}See?\n"
	.string "{JPN}Pretty easy, right?\p"
	.string "{JPN}It might be difficult to hit that\n"
	.string "{JPN}hard though, so take this!$"

ChoVillage_House5_Text_PowerGloveExplain:
	.string "{JPN}That's a glove I used whilst I was\n"
	.string "{JPN}first learning how to Rock Smash.\p"
	.string "{JPN}Any rugged rock should crumble if\n"
	.string "{JPN}you wear that Power Glove.$"

ChoVillage_House5_Text_SmashRocksEverywhere:
	.string "{JPN}Smashing rocks is really fun!\n"
	.string "{JPN}Try it everywhere you go!$"

ChoVillage_House4_Text_Zigzagoon:
	.string "{JPN}Ziguu!$"

ChoVillage_House4_Text_ImMoveTutor:
	.string "{JPN}I'm a Move Tutor!\p"
	.string "{JPN}I can teach your Pokémon a variety\n"
	.string "{JPN}of fabulous moves.\p"
	.string "{JPN}But there's a catch!\p"
	.string "{JPN}For every move I teach, you have to\n"
	.string "{JPN}give me one Big Mushroom or two\l"
	.string "{JPN}Tiny Mushrooms.$"

ChoVillage_House4_Text_NoMushrooms:
	.string "{JPN}Hmm…\p"
	.string "{JPN}You don't seem to have enough\n"
	.string "{JPN}Big or Tiny Mushrooms.\p"
	.string "{JPN}If you want me to teach a move,\n"
	.string "{JPN}then come back with some 'shrooms!$"

ChoVillage_House4_Text_HasBigMushroom:
	.string "{JPN}You have a Big Mushroom inside\n"
	.string "{JPN}your Bag, don't you?\l"
	.string "{JPN}It has a lovely scent…\p"
	.string "{JPN}In exchange for that Big Mushroom,\n"
	.string "{JPN}which move should I teach?$"

ChoVillage_House4_Text_HasTinyMushrooms:
	.string "{JPN}You have Tiny Mushrooms inside\n"
	.string "{JPN}your Bag, don't you?\l"
	.string "{JPN}They have a lovely scent…\p"
	.string "{JPN}In exchange for two Tiny Mushrooms,\n"
	.string "{JPN}which move should I teach?$"

ChoVillage_House4_Text_YouDontWantTo:
	.string "{JPN}You don't want me to teach a\n"
	.string "{JPN}move?$"

ChoVillage_House4_Text_TeachMoveToWhichMon:
	.string "{JPN}Which Pokémon should learn the\n"
	.string "{JPN}move?$"

ChoVillage_House4_Text_BigMushroomGiven:
	.string "{JPN}{PLAYER} handed over a\n"
	.string "{JPN}Big Mushroom in exchange.$"

ChoVillage_House4_Text_TinyMushroomsGiven:
	.string "{JPN}{PLAYER} handed over two\n"
	.string "{JPN}Tiny Mushrooms in exchange.$"

ChoVillage_House3_Text_HowMayIServeYou:
	.string "{JPN}Hey, {PLAYER}!\n"
	.string "{JPN}How may I serve you?$"

ChoVillage_House3_Text_NotMuchForSale:
	.string "{JPN}Man, all the vases are empty…\n"
	.string "{JPN}And the shelves are almost bare…\p"
	.string "{JPN}Looks like there isn't much for\n"
	.string "{JPN}sale around here.$"

ChoVillage_House2_Text_MechanicGreeting:
	.string "{JPN}Hey there, {PLAYER}!\n"
	.string "{JPN}Oh, you've got my delivery? Thanks!$"

ChoVillage_House2_Text_GivePackage:
	.string "{JPN}{PLAYER} gave the Berry Package\n"
	.string "{JPN}to the mechanic!$"

ChoVillage_House2_Text_BerryJam:
	.string "{JPN}Again, thank you!\p"
	.string "{JPN}Now I can make my oh-so-delicious\n"
	.string "{JPN}berry jam for my little sister.$"

ChoVillage_House2_Text_TruckBrokeDown:
	.string "{JPN}Huh? Your truck broke down?\n"
	.string "{JPN}Well, let me take a look at it!\p"
	.string "{JPN}If you can't use the truck, it'll be\n"
	.string "{JPN}totally annoying to deliver anything.\l"
	.string "{JPN}Where's it parked?$"

ChoVillage_House2_Text_IllTakeALook:
	.string "{JPN}Ah, it's parked by your place?\n"
	.string "{JPN}Alright, I'll take a look.\p"
	.string "{JPN}Don't worry!\p"
	.string "{JPN}Even if it takes a while, I'm sure\n"
	.string "{JPN}I can get it fixed!$"

ChoVillage_House2_Text_WantToFixStuff:
	.string "{JPN}When I grow up, I want to fix\n"
	.string "{JPN}stuff like my big brother!$"

ChoVillage_House1_Text_WantToRest:
	.string "{JPN}Welcome to the Cho Village Inn.\n"
	.string "{JPN}It's good to see you again, {PLAYER}.\p"
	.string "{JPN}Unfortunately, we're fully booked\n"
	.string "{JPN}for tonight, but would you like to\l"
	.string "{JPN}take a short rest free of charge?$"

ChoVillage_House1_Text_ComeAgainAnyTime:
	.string "{JPN}Come again any time.$"

ChoVillage_House1_Text_HaveAGoodRest:
	.string "{JPN}Have a good rest, {PLAYER}.$"

ChoVillage_House1_Text_HopeYouRestedWell:
	.string "{JPN}I hope you rested well.\n"
	.string "{JPN}Come again any time.$"

ChoVillage_House1_Text_OldMan:
	.string "{JPN}Why, it's {PLAYER}.\n"
	.string "{JPN}How are you doing?$"

ChoVillage_House1_Text_Lodger:
	.string "{JPN}If you stay overnight here, then\n"
	.string "{JPN}breakfast is included in your stay.\p"
	.string "{JPN}I'm glad about that, because\n"
	.string "{JPN}the cooking here is delicious!$"

OracleHill_Text_OracleGreeting:
	.string "{JPN}Young {PLAYER}…\n"
	.string "{JPN}We have not met for some time!\p"
	.string "{JPN}Are you troubled?\n"
	.string "{JPN}I would like to help however I can.\p"
	.string "{JPN}Please, sit down.$"

OracleHill_Text_OracleNext:
	.string "{JPN}So, {PLAYER}…\n"
	.string "{JPN}What is it you would like to talk about?$"

OracleHill_Text_OracleYouWannaMove:
	.string "{JPN}Oho?\n"
	.string "{JPN}You want to move to Honzhu City?\p"
	.string "{JPN}Not just that, but you want to transfer\n"
	.string "{JPN}the berry business there?\p"
	.string "{JPN}{PLAYER}…\p"
	.string "{JPN}As you and I know, we nor anybody\n"
	.string "{JPN}else in Cho Village are wealthy enough\l"
	.string "{JPN}to move out of here…$"

OracleHill_Text_OracleYourEyes:
	.string "{JPN}Your eyes, young {PLAYER}…\n"
	.string "{JPN}They project an intensity that I\l"
	.string "{JPN}haven't felt in a long time…\p"
	.string "{JPN}Why, {PLAYER}?\p"
	.string "{JPN}Village life is stable.\n"
	.string "{JPN}It is tough, but everyone, including\l"
	.string "{JPN}you, is getting by.\p"
	.string "{JPN}Not only do you lack the funds to\n"
	.string "{JPN}move, but anything could happen\l"
	.string "{JPN}out there, and we would not be able to\l"
	.string "{JPN}help you…$"

OracleHill_Text_OracleVeryWell:
	.string "{JPN}Very well…\n"
	.string "{JPN}I can feel your determination.\p"
	.string "{JPN}Money is still an issue, but\n"
	.string "{JPN}I have one idea on how you can gather\l"
	.string "{JPN}funds for your move…\p"
	.string "{JPN}There exists a popular legend around\n"
	.string "{JPN}this area.\p"
	.string "{JPN}Let me explain.$"

OracleHill_Text_OracleLegend:
	.string "{JPN}Many, many years ago, a lowly peasant\n"
	.string "{JPN}lived in this area.\p"
	.string "{JPN}Our region was ruled by a powerful\n"
	.string "{JPN}emperor who took all that people\l"
	.string "{JPN}had and left them with mere scraps.\p"
	.string "{JPN}One day, the lowly peasant unearthed a\n"
	.string "{JPN}golden relic whilst farming the fields.\p"
	.string "{JPN}The peasant wanted to sell this relic\n"
	.string "{JPN}and move up in the world, but he had\l"
	.string "{JPN}to be wary of the emperor, who was\l"
	.string "{JPN}going to the fields later that day.\p"
	.string "{JPN}So the peasant hid the relic deep\n"
	.string "{JPN}underground, and covered the hole with\l"
	.string "{JPN}earth and leaves so that it would not\l"
	.string "{JPN}stand out.\p"
	.string "{JPN}The emperor came and went with no\n"
	.string "{JPN}incident, but when the time came to\l"
	.string "{JPN}unearth the relic, it was gone!\p"
	.string "{JPN}Unfortunately for the peasant, that is\n"
	.string "{JPN}where the story ends.\p"
	.string "{JPN}He never recovered his treasure.$"

OracleHill_Text_OracleLongShot:
	.string "{JPN}It is a long shot, but perhaps this\n"
	.string "{JPN}story is real and this golden relic\l"
	.string "{JPN}is still out there.\p"
	.string "{JPN}Apart from wishing on a shooting star,\n"
	.string "{JPN}obtaining that relic and selling it is\l"
	.string "{JPN}the only way for you to gain the wealth\l"
	.string "{JPN}you need in order to move to the city.$"

OracleHill_Text_OracleCheckRuins:
	.string "{JPN}I suggest you head to the Color Ruins\n"
	.string "{JPN}as there may be more information there.\p"
	.string "{JPN}The text in the ruins is written in an\n"
	.string "{JPN}obscure language, so please take this.$"

OracleHill_Text_OracleGuideExplain:
	.string "{JPN}That should help you decipher the\n"
	.string "{JPN}language in the Color Ruins.\p"
	.string "{JPN}I was given it years ago by an old\n"
	.string "{JPN}friend of mine.\p"
	.string "{JPN}Good luck, young {PLAYER}.\n"
	.string "{JPN}I hope you can achieve your dream.$"

OracleHill_Text_OracleGoodLuck:
	.string "{JPN}Good luck, young {PLAYER}.\n"
	.string "{JPN}I hope my words have aided you.$"

DarkCity_ArumsHouse_Text_WillingToTradeIt:
	.string "{JPN}My {STR_VAR_2} is really rare…\n"
	.string "{JPN}You're jealous, aren't you?\p"
	.string "{JPN}Well, luckily for you, I'm willing\n"
	.string "{JPN}to trade it for any Pokémon you have!\p"
	.string "{JPN}So, do you want to trade?$"

DarkCity_ArumsHouse_Text_DeclinedTrade:
	.string "{JPN}You don't want to trade?\n"
	.string "{JPN}Fine! You'll be back.$"

DarkCity_ArumsHouse_Text_TradeCompleted:
	.string "{JPN}Oh, your Pokémon is pretty cool!\p"
	.string "{JPN}I'm sure it's not as cool as my\n"
	.string "{JPN}{STR_VAR_2} though, right?!$"

DarkCity_ArumsHouse_Text_PostTrade:
	.string "{JPN}How's my old {STR_VAR_2} doing?$"

DarkCity_House1_Text_GlitterYay:
	.string "{JPN}Yay! Glitter! So pretty!$"

DarkCity_House1_Text_HeresLuckyEgg:
	.string "{JPN}Are your Pokémon gaining levels\n"
	.string "{JPN}slower than you'd like?\p"
	.string "{JPN}Then take this!$"

DarkCity_House1_Text_LuckyEggGainMore:
	.string "{JPN}That's a Lucky Egg.\n"
	.string "{JPN}A Pokémon holding it will gain more\l"
	.string "{JPN}experience points in battle.$"

DarkCity_House1_Text_NoRoomForLuckyEgg:
	.string "{JPN}Oh? You don't seem to have room\n"
	.string "{JPN}for this.$"

DarkCity_House1_Text_DecorationMaker:
	.string "{JPN}I make decorations like tables and\n"
	.string "{JPN}and chairs for people's homes.\p"
	.string "{JPN}Sometimes I have to venture up\n"
	.string "{JPN}to the surface to gather materials.$"

DarkCity_House2_Text_ShopOwnerIntro:
	.string "{JPN}Oh, you're from the surface?\n"
	.string "{JPN}We just began supporting surface\l"
	.string "{JPN}currency, so feel free to shop here.$"

DarkCity_House2_Text_DecorationInfo:
	.string "{JPN}We craft these decorations out of\n"
	.string "{JPN}stone and wood we gather from the\l"
	.string "{JPN}surface about once a month.$"

DarkCity_House2_Text_ContainerInfo:
	.string "{JPN}There are about 3 shelves inside these\n"
	.string "{JPN}containers, which we fill with a layer\l"
	.string "{JPN}of fertile soil from the ground.\p"
	.string "{JPN}Then we mix in some compost and add\n"
	.string "{JPN}some seeds and fertilizer.\p"
	.string "{JPN}We can grow fruit and vegetables\n"
	.string "{JPN}even deep underground this way.\p"
	.string "{JPN}Pretty amazing, right?\p"
	.string "{JPN}But the key is using Pokémon such\n"
	.string "{JPN}as Oddish and Cherubi to help\l"
	.string "{JPN}speed up the growth of our crop.\p"
	.string "{JPN}Without Pokémon, we wouldn't be\n"
	.string "{JPN}be able to grow food at a rate at\l"
	.string "{JPN}which we could sustain ourselves.$"

DarkCity_House3_Text_ImTheMoveReminder: @ 820145C
	.string "{JPN}I'm the Move Reminder.\p"
	.string "{JPN}I know all the moves that Pokémon\n"
	.string "{JPN}learn--every one of them--and I can\l"
	.string "{JPN}teach Pokémon those moves.\p"
	.string "{JPN}I can teach a move to a Pokémon\n"
	.string "{JPN}of yours if you'd like, for free.$"

DarkCity_House3_Text_TutorWhichMon:
	.string "{JPN}Which Pokémon needs tutoring?$"

DarkCity_House3_Text_TeachWhichMove:
	.string "{JPN}Which move should I teach?$"

DarkCity_House3_Text_DontHaveMoveToTeachPokemon:
	.string "{JPN}Sorry…\p"
	.string "{JPN}It doesn't appear as if I have any move\n"
	.string "{JPN}I can teach that Pokémon.$"

DarkCity_House3_Text_ComeBackAnyTime:
	.string "{JPN}If your Pokémon need to learn a move,\n"
	.string "{JPN}come back anytime.$"

DarkCity_House3_Text_CantTeachEgg:
	.string "{JPN}Hunh? There isn't a single move that\n"
	.string "{JPN}I can teach an Egg.$"

DarkCity_House3_Text_YoureABerryFarmer:
	.string "{JPN}Oh, your clothes…\n"
	.string "{JPN}You must be a Berry farmer, right?\p"
	.string "{JPN}Haha! My intuition was spot on,\n"
	.string "{JPN}wasn't it?\p"
	.string "{JPN}I can help you draw more power out\n"
	.string "{JPN}of your Berries by teaching your\l"
	.string "{JPN}Pokémon the move Natural Gift.\p"
	.string "{JPN}Would you like me to do that?$"

DarkCity_House3_Text_NaturalGiftDeclined:
	.string "{JPN}Very well.\n"
	.string "{JPN}Come back if you change your mind.$"

DarkCity_House3_Text_NaturalGiftWhichMon:
	.string "{JPN}Which Pokémon wants to learn\n"
	.string "{JPN}Natural Gift?$"

DarkCity_House3_Text_NaturalGiftTaught:
	.string "{JPN}I hope Natural Gift comes in handy\n"
	.string "{JPN}for any future battles.\p"
	.string "{JPN}I'll teach it again any time!$"

DarkRuins_YellowRoom_Text_RoomGuide:
	.string "{JPN}In this room, you must interact\n"
	.string "{JPN}with each Diglett in a specific\l"
	.string "{JPN}order.$"

DarkRuins_YellowRoom_Text_DiglettIncorrect:
	.string "{JPN}Diiiig…$"

DarkRuins_YellowRoom_Text_DiglettCorrect:
	.string "{JPN}Dig dig!$"

DarkRuins_YellowRoom_Text_Congratulations:
	.string "{JPN}Congratulations on clearing all\n"
	.string "{JPN}the Diglett out of the way!\p"
	.string "{JPN}But to fully solve the puzzle,\n"
	.string "{JPN}you have to beat me in a battle!$"

DarkRuins_YellowRoom_Text_HuizhongDefeat:
	.string "{JPN}Hey, you're good!$"

DarkRuins_YellowRoom_Text_HuizhongPostBattle:
	.string "{JPN}Okay, okay…\n"
	.string "{JPN}I accept defeat.$"

DarkRuins_YellowRoom_Text_PuzzleComplete:
	.string "{JPN}{PLAYER} completed the puzzle!$"

DarkRuins_YellowRoom_Text_HuizhongAfter:
	.string "{JPN}I'm a Diglett fanatic, so it\n"
	.string "{JPN}was fun to wait in this room.$"

DarkRuins_GreenRoom_Text_Congratulations:
	.string "{JPN}Con… grat… ulations…\n"
	.string "{JPN}Urrrrrp…\p"
	.string "{JPN}Watching… you… spin…\n"
	.string "{JPN}made… me… really… sick…$"

DarkRuins_GreenRoom_Text_AfterPuzzleComplete:
	.string "{JPN}No… more… spinning… please…!$"

DarkRuins_RedRoom_Text_RoomGuide:
	.string "{JPN}These boulders are replicas, so\n"
	.string "{JPN}you should be able to move them\l"
	.string "{JPN}with ease.$"

DarkRuins_RedRoom_Text_Congratulations:
	.string "{JPN}You pushed your way to victory!\n"
	.string "{JPN}Congratulations!\p"
	.string "{JPN}But now, you need to push past\n"
	.string "{JPN}my powerful Pokémon team!$"

DarkRuins_RedRoom_Text_BaozhaiDefeat:
	.string "{JPN}I hope I could push you to your\n"
	.string "{JPN}limits!$"

DarkRuins_RedRoom_Text_BaozhaiPostBattle:
	.string "{JPN}Okay, good job.\n"
	.string "{JPN}You're tough!$"

DarkRuins_RedRoom_Text_BaozhaiAfter:
	.string "{JPN}Real boulders aren't as easy to\n"
	.string "{JPN}push as these replicas.$"

DarkRuins_BlueRoom_EventScript_Text_Pattern1:
	.string "{JPN}C D c A B E F G$"

DarkRuins_BlueRoom_EventScript_Text_Pattern2:
	.string "{JPN}c B E A G F D C$"

DarkRuins_BlueRoom_EventScript_Text_Pattern3:
	.string "{JPN}F E D G c A C B$"

DarkRuins_BlueRoom_Text_Congratulations:
	.string "{JPN}Congratulations on making it to me!\p"
	.string "{JPN}I forgot to bring my Pokémon,\n"
	.string "{JPN}so you won't have to battle me.$"

DarkRuins_BlueRoom_Text_AfterPuzzleComplete:
	.string "{JPN}According to Arum, these note mats\n"
	.string "{JPN}are really expensive.\p"
	.string "{JPN}He said he got them from some exotic\n"
	.string "{JPN}foreign region or something.$"

DarkRuins_FinalRoom_Text_ArumIntro:
	.string "{JPN}How incredible!\n"
	.string "{JPN}You've completed all of my puzzles!\p"
	.string "{JPN}You are truly interesting, {PLAYER}…\p"
	.string "{JPN}But you're not just here to complete\n"
	.string "{JPN}puzzles, are you?\l"
	.string "{JPN}I promised you a reward…\l"
	.string "{JPN}But the fun isn't over yet!\n"
	.string "{JPN}Your final test… is a battle!\p"
	.string "{JPN}If you can defeat me, then the\n"
	.string "{JPN}Relic Crown is yours!$"

DarkRuins_FinalRoom_Text_ArumDefeat:
	.string "{JPN}My, {PLAYER}…\n"
	.string "{JPN}How strong you are!$"

DarkRuins_FinalRoom_Text_ArumPostBattle:
	.string "{JPN}Hahaha!\n"
	.string "{JPN}That battle was the best!\p"
	.string "{JPN}Not only are you a puzzle genius,\n"
	.string "{JPN}but you're a seasoned battler too!\p"
	.string "{JPN}Very well! This is yours!$"

DarkRuins_FinalRoom_Text_ArumNext:
	.string "{JPN}That is indeed the Relic Crown!\n"
	.string "{JPN}Take a look at its magnificence!\p"
	.string "{JPN}It is yours to do whatever you\n"
	.string "{JPN}please with.\p"
	.string "{JPN}I was searching for a long time\n"
	.string "{JPN}for someone who could solve my\l"
	.string "{JPN}expertly-crafted puzzles.\p"
	.string "{JPN}And I finally found him.\n"
	.string "{JPN}That satisifies me.\p"
	.string "{JPN}Oh, but I'm rambling now.\p"
	.string "{JPN}Now that the Crown is yours,\n"
	.string "{JPN}you must be looking to return\l"
	.string "{JPN}to the surface.\p"
	.string "{JPN}I'm willing to take you back\n"
	.string "{JPN}whenever you'd like.\p"
	.string "{JPN}However, you can't come back,\n"
	.string "{JPN}so make sure you finish what\l"
	.string "{JPN}you need to down here.\p"
	.string "{JPN}Do you understand?\p"
	.string "{JPN}If there is anything you need\n"
	.string "{JPN}to still do down here, do it now.$"

DarkRuins_FinalRoom_Text_ArumWantToReturn:
	.string "{JPN}Would you like to return to the\n"
	.string "{JPN}surface?$"

DarkRuins_FinalRoom_Text_ArumTakeYourTime:
	.string "{JPN}Take your time.\n"
	.string "{JPN}I'm in no rush.$"

DarkRuins_FinalRoom_Text_ArumLetsGo:
	.string "{JPN}Okay, let's go!$"