@ story text

JamKeyMap_Text_Mechanic:
	.string "Hmm…\n"
	.string "This is gonna be a tough one…$"

JamKeyMap_Text_MechanicHey:
	.string "Hey, {PLAYER}!\n"
	.string "Over here!$"

JamKeyMap_Text_GoodAsNew:
	.string "The truck is up and running!\n"
	.string "She's as good as new!\l"
	.string "I knew I could get it working again.\p"
	.string "It did take a while, I had to mess\n"
	.string "with the exhaust a little bit and\l"
	.string "replace the battery, but here she is!\p"
	.string "You just come find me if you ever\n"
	.string "need any more help!$"

JamKeyMap_Text_CantLeave:
	.string "I can't leave!\n"
	.string "I need to get in the truck.$"

JamKeyMap_Text_TruckWontStart:
	.string "The truck won't start.\n"
	.string "It seems to be broken.$"

JamKeyMap_Text_PulpUrgh:
	.string "The truck won't start!\p"
	.string "Looks like {PLAYER} has to travel\n"
	.string "to Cho Village in the east on foot.$"

JamKeyMap_Text_LogPleaseBattleMe:
	.string "Oh, it's {PLAYER}!\n"
	.string "How's it going?\p"
	.string "W-whaat?!\n"
	.string "You actually found that relic?!\l"
	.string "T-that's incredible!\p"
	.string "So, I guess you're… going?\p"
	.string "Before you go, {PLAYER}…\n"
	.string "Let's have another battle.\p"
	.string "But this time, I'll win!\p"
	.string "I'll let you prepare, so talk\n"
	.string "to me when you're ready to fight.$"

JamKeyMap_Text_LogIntro:
	.string "Well then, {PLAYER}!\n"
	.string "Our final fight… here I come!$"

JamKeyMap_Text_LogDefeat:
	.string "Aha, nothing's changed!$"

JamKeyMap_Text_LogPostBattle:
	.string "Like always, you win…\n"
	.string "But I don't care!\p"
	.string "I just like to battle, whether\n"
	.string "I win or lose!\p"
	.string "My Pokémon feel the same way.\p"
	.string "So, looks like this is goodbye…\n"
	.string "I'm not jealous or anything.\p"
	.string "I can find meaning in my construction\n"
	.string "work, so I'm happy right here!\p"
	.string "Yup, so go ahead and enjoy yourself\n"
	.string "in big ol' Honzhu City!\n"
	.string "Make sure you work hard on the\n"
	.string "Berry business too, though!\p"
	.string "And send me a postcard when you\n"
	.string "get there!\p"
	.string "Well, old friend…\n"
	.string "Farewell!$"

FarmerField_Text_MyNameIsPulp:
	.string "My name is Pulp.$"

FarmerField_Text_RuralFarmer:
	.string "I'm a farmer in a rural, poor\n"
	.string "area in the middle of nowhere.$"

FarmerField_Text_BerryFarmer:
	.string "Specifically, I'm a Berry farmer.$"

FarmerField_Text_EveryoneHasAJob:
	.string "Everyone here has a job, and mine\n"
	.string "is to grow Berries and sell them.$"

FarmerField_Text_LifeIsTough:
	.string "Life is tough here.\n"
	.string "All of us have to work hard to survive.$"

FarmerField_Text_GoWithoutFood:
	.string "If you can't work, then you can't make\n"
	.string "money, and you have to go without food.$"

FarmerField_Text_HaveADream:
	.string "But I have a dream!$"

FarmerField_Text_DontKnowHow:
	.string "I don't know how to achieve it, but…$"

FarmerField_Text_WantToGetAway:
	.string "I want to escape this rural lifestyle.\p"
	.string "I want to grow Berries on a\n"
	.string "wider scale.$"

FarmerField_Text_WantToMoveCity:
	.string "I want to move to Honzhu City,\n"
	.string "a gigantic city in the south!$"

FarmerField_Text_CityIsAmazing:
	.string "Honzhu City is amazing.\p"
	.string "It's a bustling metropolis with\n"
	.string "opportunities to do all kinds of things.\p"
	.string "It's a very rich city full of\n"
	.string "all kinds of people.\p"
	.string "My late father told me stories of\n"
	.string "Honzhu, as he got to visit once\l"
	.string "when he was a young man.\p"
	.string "And since then, it's been my dream\n"
	.string "to escape this place and move there.$"

FarmerField_Text_AllDone:
	.string "…All done!\p"
	.string "Finally, I managed to pick all the\n"
	.string "Berries for the mechanic's order.\p"
	.string "Now to get in the truck and deliver\n"
	.string "it to him!$"

ShendownPath_Text_Sign:
	.string "Shendown Path$"

ShendownPath_Text_Fisherman:
	.string "Pokémon battle?\p"
	.string "{PLAYER}, you know I'm not\n"
	.string "into that stuff at all!\p"
	.string "No, all I want to do is fish!\n"
	.string "All day and all night!\p"
	.string "You should give up farming and\n"
	.string "come be a fisherman with me!$"

ChoVillage_Text_InnSign:
	.string "Cho Village Inn$"

ChoVillage_Text_Man:
	.string "Hey there, {PLAYER}!$"

ChoVillage_Text_Woman:
	.string "Good day, {PLAYER}.\n"
	.string "I heard the Berry harvest this year\l"
	.string "is going well. Good for you!$"

ChoVillage_Text_ComplainingFisherman:
	.string "Argh, I can't catch any fish at all!\p"
	.string "It must be because of all those\n"
	.string "Grimer polluting the river!$"

ChoVillage_Text_EarlyLogIntro:
	.string "Yo, it's {PLAYER}!\n"
	.string "How's it going, old friend?\l"
	.string "I just got back from work!\p"
	.string "Of course, now that our eyes have\n"
	.string "met, we've got to have a battle, right?!$"

ChoVillage_Text_EarlyLogDefeat:
	.string "No way, that was a fluke!$"

ChoVillage_Text_EarlyLogPostBattle:
	.string "I thought I was going to win\n"
	.string "this time for sure…\p"
	.string "Anyway, how come you're not driving\n"
	.string "here in the truck today?\p"
	.string "Huh? It's broken down?\p"
	.string "Looks like you'd better go see the\n"
	.string "mechanic. He lives in the north-west\l"
	.string "of the village.\p"
	.string "If anyone can fix your truck, it'll\n"
	.string "be that guy.\p"
	.string "By the way, I was thinking about\n"
	.string "what you told me the other day.\p"
	.string "You said you wanted to move to the\n"
	.string "city, and I was all for it, but…\p"
	.string "Now that I think about it, moving\n"
	.string "to the city requires so much money,\l"
	.string "more money than we'd make in a decade…\p"
	.string "Oh, I have an idea.\n"
	.string "You should go and see the Oracle.\p"
	.string "He might have an idea on how you could\n"
	.string "get enough money to move to the city.\p"
	.string "Anyhow, I've got to go!\p"
	.string "Can't spend too much time dawdling,\n"
	.string "because time is money! See ya!$"

ChoVillage_Text_LogIntro:
	.string "Yo, {PLAYER}!\n"
	.string "Fancy seeing you again so soon!\p"
	.string "So, did you speak to the Oracle?$"

ChoVillage_Text_LogNext:
	.string "You did?\n"
	.string "And now you're investigating the\l"
	.string "Color Ruins? Sounds fun!\p"
	.string "But if you're planning to go to all of\n"
	.string "the Color Ruins, you're out of luck!\p"
	.string "You can't get to the red Color Ruins on\n"
	.string "foot because the river is in the way!\p"
	.string "Luckily for you, your best friend, me,\n"
	.string "specializes in building bridges!\p"
	.string "Yup, your dreams are my dreams, buddy,\n"
	.string "so I'll go and build a bridge to the\l"
	.string "red Color Ruins on Shendown Path.\l"
	.string "It might take a little while though!\p"
	.string "I've got yet another job to get to, so\n"
	.string "I'll speak to you again later! See ya!$"

ChoVillage_Text_WantMorePeopleFish:
	.string "I want more young people to fish.\n"
	.string "Do you want to learn to fish?$"

ChoVillage_Text_MyOldFishingRod:
	.string "Very good!\n"
	.string "Here, take my old fishing rod.$"

ChoVillage_Text_FishingMaySeemDifficult:
	.string "Now, fishing may seem difficult,\n"
	.string "but it's actually very simple.\p"
	.string "First, you want to face the water,\n"
	.string "then use the rod.\p"
	.string "Focus your mind…\n"
	.string "If you get a bite, pull on the rod.\p"
	.string "Sometimes you can snag something\n"
	.string "immediately, but with bigger catches,\l"
	.string "you need to time the pulls on your rod\l"
	.string "to haul them in.$"

ChoVillage_Text_ThatsTooBadThen:
	.string "Oh, is that so?\n"
	.string "That's too bad, then.$"

ChoVillage_Text_HowsYourFishing:
	.string "Yo!\n"
	.string "How's your fishing?$"

ChoVillage_Text_GreatHaulInSomeBigOnes:
	.string "Is that right! That's great!\n"
	.string "Haul in some big ones!$"

ChoVillage_Text_TimingYourPulls:
	.string "Remember, timing your pulls\n"
	.string "is key when it comes to fishing.$"

WangyongMarsh_Text_ThinkingMan:
	.string "Our Cho Village is just a tiny,\n"
	.string "isolated part of a huge region…\p"
	.string "There's still a lot of things\n"
	.string "we have no idea about.\p"
	.string "I wonder what else the world holds.$"

KimyangRoad_Text_ItemfinderIntro:
	.string "Are you looking for items\n"
	.string "hidden around the field?\p"
	.string "Then take this!$"

KimyangRoad_Text_ItemfinderExplain:
	.string "That's an Itemfinder.\n"
	.string "I got it when I took a trip\l"
	.string "to Honzhu City in the south.\p"
	.string "It reacts when hidden items are\n"
	.string "detected, so it's really useful.$"

KimyangRoad_Text_ItemfinderRecieved:
	.string "There are items hidden everywhere.\n"
	.string "You should use the Itemfinder often!$"

OracleHill_Text_OldWoman:
	.string "Fu fu fu fu…\p"
	.string "This path leads to the Oracle's cave.\p"
	.string "But I'm sure you knew that, didn't you?$"

OracleHill_Text_CaveRoadblock:
	.string "I'm sorry, but the Oracle is at\n"
	.string "a ceremony right now…\p"
	.string "He will be back shortly, but surely\n"
	.string "you have errands to run in the\l"
	.string "meantime, hmm?$"

ZhaounPath_Text_NoTallGrass:
	.string "There isn't much tall grass here…\n"
	.string "Did somebody cut it all down?$"

DarkCityEntrance_Text_ArumStrangeSound:
	.string "I heard a strange sound, so I came.\n"
	.string "And look what I've found!\p"
	.string "Where did you come from, son?\p"
	.string "Oh? You fell through the floor in\n"
	.string "the blue Color Ruins? I see…\p"
	.string "My name is Arum.\n"
	.string "And this is the Dark City!$"

DarkCityEntrance_Text_ArumExplain:
	.string "Hm? You look confused.\n"
	.string "Let me explain a little more.\p"
	.string "Many decades ago, our ancestors\n"
	.string "wanted to build a successor to\l"
	.string "the Color Ruins deep underground.\p"
	.string "At the time, there was lots of\n"
	.string "political tension on the surface,\l"
	.string "and everyone was on edge.\p"
	.string "So our ancestors decided to not\n"
	.string "just build a Ruins underground, but\l"
	.string "to build an entire civilisation!\p"
	.string "We're rather isolated from the\n"
	.string "rest of the world down here.\p"
	.string "However, we do have our ways of\n"
	.string "getting back to the surface.\p"
	.string "Anyway, you said you fell through\n"
	.string "the blue Color Ruins, right?\l"
	.string "Why on earth were you in there?$"

DarkCityEntrance_Text_ArumRelic:
	.string "Searching for a golden relic, huh?\n"
	.string "Well, you got lucky, son!\l"
	.string "That old legend is true!\p"
	.string "The Relic Crown has been passed from\n"
	.string "person to person for many centuries.\p"
	.string "I am its current owner!\p"
	.string "If you want to know more, then follow\n"
	.string "me to the Dark City's main chamber!$"

DarkCityMain_Text_HotSpringInfo:
	.string "This hot spring has healing properties.\p"
	.string "If you take a dip in it, then your\n"
	.string "Pokémon team's health will be restored.$"

DarkCityMain_Text_CaveLover:
	.string "I was born and raised in Dark City,\n"
	.string "but I occasionally explore the surface.\p"
	.string "However, as a lover of caves, this\n"
	.string "is a perfect place for me to live.$"

DarkCityMain_Text_MoneyRare:
	.string "We don't use money much in this city.\n"
	.string "Most of the time, we barter goods.$"

DarkCityMain_Text_WomanBathingInSpring:
	.string "Ah… that hits the spot…$"

DarkCityMain_Text_ShopSign:
	.string "DARK CITY GENERAL STORE\n"
	.string "NOW ACCEPTING SURFACE CURRENCY$"

DarkCityMain_Text_PokemonHealed:
	.string "Your Pokémon were restored to full\n"
	.string "health!$"

DarkCityMain_Text_ArumSoCool:
	.string "Arum is so cool…\n"
	.string "He's the strongest Trainer ever!$"

DarkCityMain_Text_RelicCrownInfo:
	.string "My Relic Crown is indeed the golden\n"
	.string "relic from that ancient story.\p"
	.string "I found it five years ago on an\n"
	.string "excursion I took to a mountain in\l"
	.string "the east.\p"
	.string "You want the Crown, don't you?\n"
	.string "I can see it in your eyes…\p"
	.string "For years, people have been trying\n"
	.string "to buy the Relic Crown off of me.\p"
	.string "But I will not sell out so easily!\n"
	.string "Money is of no concern to me, anyway.\p"
	.string "No, what I care about is puzzles!\p"
	.string "Do you remember the puzzles you had\n"
	.string "to solve in order to explore the\l"
	.string "back caves of the Color Ruins?\p"
	.string "I created many puzzles just like\n"
	.string "them and filled the Dark Ruins behind\l"
	.string "me with them.\p"
	.string "If you want the Relic Crown, you must\n"
	.string "solve all of these puzzles!\p"
	.string "Follow me, uh…$"

DarkCityMain_Text_ForgotToAskName:
	.string "Oh, so sorry!\n"
	.string "I didn't even ask your name!$"

DarkCityMain_Text_PulpIsIt:
	.string "{PLAYER}, is it?\n"
	.string "Follow me!$"

DarkRuins_Text_ArumExplanation:
	.string "Welcome to the Dark Ruins!\p"
	.string "Each room in here has a puzzle\n"
	.string "expertly crafted by yours truly!\p"
	.string "If you can solve all four puzzles,\n"
	.string "the Relic Crown will be your reward.\p"
	.string "Nobody has ever been able to solve\n"
	.string "all four of my puzzles, so you have\l"
	.string "quite the challenge ahead of you!$"

DarkRuins_Text_ArumWaitAtEnd:
	.string "I'll be waiting inside this room,\n"
	.string "which will close once I step inside.\p"
	.string "It will reopen once you've solved\n"
	.string "all four puzzles.\p"
	.string "Good luck, {PLAYER}…$"

LinkingTunnel_Text_DiglettAsleep:
	.string "The Diglett is sleeping soundly.$"

LinkingTunnel_Text_DiglettBlockingWay:
	.string "I wanted to get to Zhaoun Path, but\n"
	.string "these Diglett are blocking the way!\p"
	.string "I'm sure they'll wake up and move\n"
	.string "soon enough, though.$"

ChoVillage_House5_Text_WhatIsStrength:
	.string "What is strength?\p"
	.string "Obviously, it's the ability\n"
	.string "to clear obstacles in your way!\p"
	.string "Have you ever noticed rugged\n"
	.string "rocks in the field?\p"
	.string "I'll teach you how to smash those\n"
	.string "rocks if you tell me what lies inside\l"
	.string "the yellow Color Ruins!\p"
	.string "Please!\n"
	.string "I've always wanted to know!$"

ChoVillage_House5_Text_TellAboutRuins:
	.string "What?!\p"
	.string "There's a secret cave behind the\n"
	.string "walls of the yellow Color Ruins?!\p"
	.string "I thought that there would totally\n"
	.string "be a pot of gold or something!\p"
	.string "Well, whatever.\n"
	.string "You came to learn how to smash rocks,\l"
	.string "so I'll teach you the art of Rock Smash!$"

ChoVillage_House5_Text_RockSmashTutorial:
	.string "Rock Smash is actually pretty simple.\p"
	.string "Tense your muscles, and then…$"

ChoVillage_House5_Text_Wacha:
	.string "Wachaaaa!$"

ChoVillage_House5_Text_SeePrettyEasy:
	.string "See?\n"
	.string "Pretty easy, right?\p"
	.string "It might be difficult to hit that\n"
	.string "hard though, so take this!$"

ChoVillage_House5_Text_PowerGloveExplain:
	.string "That's a glove I used whilst I was\n"
	.string "first learning how to Rock Smash.\p"
	.string "Any rugged rock should crumble if\n"
	.string "you wear that Power Glove.$"

ChoVillage_House5_Text_SmashRocksEverywhere:
	.string "Smashing rocks is really fun!\n"
	.string "Try it everywhere you go!$"

ChoVillage_House4_Text_Zigzagoon:
	.string "Ziguu!$"

ChoVillage_House4_Text_ImMoveTutor:
	.string "I'm a Move Tutor!\p"
	.string "I can teach your Pokémon a variety\n"
	.string "of fabulous moves.\p"
	.string "But there's a catch!\p"
	.string "For every move I teach, you have to\n"
	.string "give me one Big Mushroom or two\l"
	.string "Tiny Mushrooms.$"

ChoVillage_House4_Text_NoMushrooms:
	.string "Hmm…\p"
	.string "You don't seem to have enough\n"
	.string "Big or Tiny Mushrooms.\p"
	.string "If you want me to teach a move,\n"
	.string "then come back with some 'shrooms!$"

ChoVillage_House4_Text_HasBigMushroom:
	.string "You have a Big Mushroom inside\n"
	.string "your Bag, don't you?\l"
	.string "It has a lovely scent…\p"
	.string "In exchange for that Big Mushroom,\n"
	.string "which move should I teach?$"

ChoVillage_House4_Text_HasTinyMushrooms:
	.string "You have Tiny Mushrooms inside\n"
	.string "your Bag, don't you?\l"
	.string "They have a lovely scent…\p"
	.string "In exchange for two Tiny Mushrooms,\n"
	.string "which move should I teach?$"

ChoVillage_House4_Text_YouDontWantTo:
	.string "You don't want me to teach a\n"
	.string "move?$"

ChoVillage_House4_Text_TeachMoveToWhichMon:
	.string "Which Pokémon should learn the\n"
	.string "move?$"

ChoVillage_House4_Text_BigMushroomGiven:
	.string "{PLAYER} handed over a\n"
	.string "Big Mushroom in exchange.$"

ChoVillage_House4_Text_TinyMushroomsGiven:
	.string "{PLAYER} handed over two\n"
	.string "Tiny Mushrooms in exchange.$"

ChoVillage_House3_Text_HowMayIServeYou:
	.string "Hey, {PLAYER}!\n"
	.string "How may I serve you?$"

ChoVillage_House3_Text_NotMuchForSale:
	.string "Man, all the vases are empty…\n"
	.string "And the shelves are almost bare…\p"
	.string "Looks like there isn't much for\n"
	.string "sale around here.$"

ChoVillage_House2_Text_MechanicGreeting:
	.string "Hey there, {PLAYER}!\n"
	.string "Oh, you've got my delivery? Thanks!$"

ChoVillage_House2_Text_GivePackage:
	.string "{PLAYER} gave the Berry Package\n"
	.string "to the mechanic!$"

ChoVillage_House2_Text_BerryJam:
	.string "Again, thank you!\p"
	.string "Now I can make my oh-so-delicious\n"
	.string "berry jam for my little sister.$"

ChoVillage_House2_Text_TruckBrokeDown:
	.string "Huh? Your truck broke down?\n"
	.string "Well, let me take a look at it!\p"
	.string "If you can't use the truck, it'll be\n"
	.string "totally annoying to deliver anything.\l"
	.string "Where's it parked?$"

ChoVillage_House2_Text_IllTakeALook:
	.string "Ah, it's parked by your place?\n"
	.string "Alright, I'll take a look.\p"
	.string "Don't worry!\p"
	.string "Even if it takes a while, I'm sure\n"
	.string "I can get it fixed!$"

ChoVillage_House2_Text_WantToFixStuff:
	.string "When I grow up, I want to fix\n"
	.string "stuff like my big brother!$"

ChoVillage_House1_Text_WantToRest:
	.string "Welcome to the Cho Village Inn.\n"
	.string "It's good to see you again, {PLAYER}.\p"
	.string "Unfortunately, we're fully booked\n"
	.string "for tonight, but would you like to\l"
	.string "take a short rest free of charge?$"

ChoVillage_House1_Text_ComeAgainAnyTime:
	.string "Come again any time.$"

ChoVillage_House1_Text_HaveAGoodRest:
	.string "Have a good rest, {PLAYER}.$"

ChoVillage_House1_Text_HopeYouRestedWell:
	.string "I hope you rested well.\n"
	.string "Come again any time.$"

ChoVillage_House1_Text_OldMan:
	.string "Why, it's {PLAYER}.\n"
	.string "How are you doing?$"

ChoVillage_House1_Text_Lodger:
	.string "If you stay overnight here, then\n"
	.string "breakfast is included in your stay.\p"
	.string "I'm glad about that, because\n"
	.string "the cooking here is delicious!$"

OracleHill_Text_OracleGreeting:
	.string "Young {PLAYER}…\n"
	.string "We have not met for some time!\p"
	.string "Are you troubled?\n"
	.string "I would like to help however I can.\p"
	.string "Please, sit down.$"

OracleHill_Text_OracleNext:
	.string "So, {PLAYER}…\n"
	.string "What is it you would like to talk about?$"

OracleHill_Text_OracleYouWannaMove:
	.string "Oho?\n"
	.string "You want to move to Honzhu City?\p"
	.string "Not just that, but you want to transfer\n"
	.string "the berry business there?\p"
	.string "{PLAYER}…\p"
	.string "As you and I know, we nor anybody\n"
	.string "else in Cho Village are wealthy enough\l"
	.string "to move out of here…$"

OracleHill_Text_OracleYourEyes:
	.string "Your eyes, young {PLAYER}…\n"
	.string "They project an intensity that I\l"
	.string "haven't felt in a long time…\p"
	.string "Why, {PLAYER}?\p"
	.string "Village life is stable.\n"
	.string "It is tough, but everyone, including\l"
	.string "you, is getting by.\p"
	.string "Not only do you lack the funds to\n"
	.string "move, but anything could happen\l"
	.string "out there, and we would not be able to\l"
	.string "help you…$"

OracleHill_Text_OracleVeryWell:
	.string "Very well…\n"
	.string "I can feel your determination.\p"
	.string "Money is still an issue, but\n"
	.string "I have one idea on how you can gather\l"
	.string "funds for your move…\p"
	.string "There exists a popular legend around\n"
	.string "this area.\p"
	.string "Let me explain.$"

OracleHill_Text_OracleLegend:
	.string "Many, many years ago, a lowly peasant\n"
	.string "lived in this area.\p"
	.string "Our region was ruled by a powerful\n"
	.string "emperor who took all that people\l"
	.string "had and left them with mere scraps.\p"
	.string "One day, the lowly peasant unearthed a\n"
	.string "golden relic whilst farming the fields.\p"
	.string "The peasant wanted to sell this relic\n"
	.string "and move up in the world, but he had\l"
	.string "to be wary of the emperor, who was\l"
	.string "going to the fields later that day.\p"
	.string "So the peasant hid the relic deep\n"
	.string "underground, and covered the hole with\l"
	.string "earth and leaves so that it would not\l"
	.string "stand out.\p"
	.string "The emperor came and went with no\n"
	.string "incident, but when the time came to\l"
	.string "unearth the relic, it was gone!\p"
	.string "Unfortunately for the peasant, that is\n"
	.string "where the story ends.\p"
	.string "He never recovered his treasure.$"

OracleHill_Text_OracleLongShot:
	.string "It is a long shot, but perhaps this\n"
	.string "story is real and this golden relic\l"
	.string "is still out there.\p"
	.string "Apart from wishing on a shooting star,\n"
	.string "obtaining that relic and selling it is\l"
	.string "the only way for you to gain the wealth\l"
	.string "you need in order to move to the city.$"

OracleHill_Text_OracleCheckRuins:
	.string "I suggest you head to the Color Ruins\n"
	.string "as there may be more information there.\p"
	.string "The text in the ruins is written in an\n"
	.string "obscure language, so please take this.$"

OracleHill_Text_OracleGuideExplain:
	.string "That should help you decipher the\n"
	.string "language in the Color Ruins.\p"
	.string "I was given it years ago by an old\n"
	.string "friend of mine.\p"
	.string "Good luck, young {PLAYER}.\n"
	.string "I hope you can achieve your dream.$"

OracleHill_Text_OracleGoodLuck:
	.string "Good luck, young {PLAYER}.\n"
	.string "I hope my words have aided you.$"

DarkCity_ArumsHouse_Text_WillingToTradeIt:
	.string "My {STR_VAR_2} is really rare…\n"
	.string "You're jealous, aren't you?\p"
	.string "Well, luckily for you, I'm willing\n"
	.string "to trade it for any Pokémon you have!\p"
	.string "So, do you want to trade?$"

DarkCity_ArumsHouse_Text_DeclinedTrade:
	.string "You don't want to trade?\n"
	.string "Fine! You'll be back.$"

DarkCity_ArumsHouse_Text_TradeCompleted:
	.string "Oh, your Pokémon is pretty cool!\p"
	.string "I'm sure it's not as cool as my\n"
	.string "{STR_VAR_2} though, right?!$"

DarkCity_ArumsHouse_Text_PostTrade:
	.string "How's my old {STR_VAR_2} doing?$"

DarkCity_House1_Text_GlitterYay:
	.string "Yay! Glitter! So pretty!$"

DarkCity_House1_Text_HeresLuckyEgg:
	.string "Are your Pokémon gaining levels\n"
	.string "slower than you'd like?\p"
	.string "Then take this!$"

DarkCity_House1_Text_LuckyEggGainMore:
	.string "That's a Lucky Egg.\n"
	.string "A Pokémon holding it will gain more\l"
	.string "experience points in battle.$"

DarkCity_House1_Text_NoRoomForLuckyEgg:
	.string "Oh? You don't seem to have room\n"
	.string "for this.$"

DarkCity_House1_Text_DecorationMaker:
	.string "I make decorations like tables and\n"
	.string "and chairs for people's homes.\p"
	.string "Sometimes I have to venture up\n"
	.string "to the surface to gather materials.$"

DarkCity_House2_Text_ShopOwnerIntro:
	.string "Oh, you're from the surface?\n"
	.string "We just began supporting surface\l"
	.string "currency, so feel free to shop here.$"

DarkCity_House2_Text_DecorationInfo:
	.string "We craft these decorations out of\n"
	.string "stone and wood we gather from the\l"
	.string "surface about once a month.$"

DarkCity_House2_Text_ContainerInfo:
	.string "There are about 3 shelves inside these\n"
	.string "containers, which we fill with a layer\l"
	.string "of fertile soil from the ground.\p"
	.string "Then we mix in some compost and add\n"
	.string "some seeds and fertilizer.\p"
	.string "We can grow fruit and vegetables\n"
	.string "even deep underground this way.\p"
	.string "Pretty amazing, right?\p"
	.string "But the key is using Pokémon such\n"
	.string "as Oddish and Cherubi to help\l"
	.string "speed up the growth of our crop.\p"
	.string "Without Pokémon, we wouldn't be\n"
	.string "be able to grow food at a rate at\l"
	.string "which we could sustain ourselves.$"

DarkCity_House3_Text_ImTheMoveReminder: @ 820145C
	.string "I'm the Move Reminder.\p"
	.string "I know all the moves that Pokémon\n"
	.string "learn--every one of them--and I can\l"
	.string "teach Pokémon those moves.\p"
	.string "I can teach a move to a Pokémon\n"
	.string "of yours if you'd like, for free.$"

DarkCity_House3_Text_TutorWhichMon:
	.string "Which Pokémon needs tutoring?$"

DarkCity_House3_Text_TeachWhichMove:
	.string "Which move should I teach?$"

DarkCity_House3_Text_DontHaveMoveToTeachPokemon:
	.string "Sorry…\p"
	.string "It doesn't appear as if I have any move\n"
	.string "I can teach that Pokémon.$"

DarkCity_House3_Text_ComeBackAnyTime:
	.string "If your Pokémon need to learn a move,\n"
	.string "come back anytime.$"

DarkCity_House3_Text_CantTeachEgg:
	.string "Hunh? There isn't a single move that\n"
	.string "I can teach an Egg.$"

DarkCity_House3_Text_YoureABerryFarmer:
	.string "Oh, your clothes…\n"
	.string "You must be a Berry farmer, right?\p"
	.string "Haha! My intuition was spot on,\n"
	.string "wasn't it?\p"
	.string "I can help you draw more power out\n"
	.string "of your Berries by teaching your\l"
	.string "Pokémon the move Natural Gift.\p"
	.string "Would you like me to do that?$"

DarkCity_House3_Text_NaturalGiftDeclined:
	.string "Very well.\n"
	.string "Come back if you change your mind.$"

DarkCity_House3_Text_NaturalGiftWhichMon:
	.string "Which Pokémon wants to learn\n"
	.string "Natural Gift?$"

DarkCity_House3_Text_NaturalGiftTaught:
	.string "I hope Natural Gift comes in handy\n"
	.string "for any future battles.\p"
	.string "I'll teach it again any time!$"

DarkRuins_YellowRoom_Text_RoomGuide:
	.string "In this room, you must interact\n"
	.string "with each Diglett in a specific\l"
	.string "order.$"

DarkRuins_YellowRoom_Text_DiglettIncorrect:
	.string "Diiiig…$"

DarkRuins_YellowRoom_Text_DiglettCorrect:
	.string "Dig dig!$"

DarkRuins_YellowRoom_Text_Congratulations:
	.string "Congratulations on clearing all\n"
	.string "the Diglett out of the way!\p"
	.string "But to fully solve the puzzle,\n"
	.string "you have to beat me in a battle!$"

DarkRuins_YellowRoom_Text_HuizhongDefeat:
	.string "Hey, you're good!$"

DarkRuins_YellowRoom_Text_HuizhongPostBattle:
	.string "Okay, okay…\n"
	.string "I accept defeat.$"

DarkRuins_YellowRoom_Text_PuzzleComplete:
	.string "{PLAYER} completed the puzzle!$"

DarkRuins_YellowRoom_Text_HuizhongAfter:
	.string "I'm a Diglett fanatic, so it\n"
	.string "was fun to wait in this room.$"

DarkRuins_GreenRoom_Text_Congratulations:
	.string "Con… grat… ulations…\n"
	.string "Urrrrrp…\p"
	.string "Watching… you… spin…\n"
	.string "made… me… really… sick…$"

DarkRuins_GreenRoom_Text_AfterPuzzleComplete:
	.string "No… more… spinning… please…!$"

DarkRuins_RedRoom_Text_RoomGuide:
	.string "These boulders are replicas, so\n"
	.string "you should be able to move them\l"
	.string "with ease.$"

DarkRuins_RedRoom_Text_Congratulations:
	.string "You pushed your way to victory!\n"
	.string "Congratulations!\p"
	.string "But now, you need to push past\n"
	.string "my powerful Pokémon team!$"

DarkRuins_RedRoom_Text_BaozhaiDefeat:
	.string "I hope I could push you to your\n"
	.string "limits!$"

DarkRuins_RedRoom_Text_BaozhaiPostBattle:
	.string "Okay, good job.\n"
	.string "You're tough!$"

DarkRuins_RedRoom_Text_BaozhaiAfter:
	.string "Real boulders aren't as easy to\n"
	.string "push as these replicas.$"

DarkRuins_BlueRoom_EventScript_Text_Pattern1:
	.string "C D c A B E F G$"

DarkRuins_BlueRoom_EventScript_Text_Pattern2:
	.string "c B E A G F D C$"

DarkRuins_BlueRoom_EventScript_Text_Pattern3:
	.string "F E D G c A C B$"

DarkRuins_BlueRoom_Text_Congratulations:
	.string "Congratulations on making it to me!\p"
	.string "I forgot to bring my Pokémon,\n"
	.string "so you won't have to battle me.$"

DarkRuins_BlueRoom_Text_AfterPuzzleComplete:
	.string "According to Arum, these note mats\n"
	.string "are really expensive.\p"
	.string "He said he got them from some exotic\n"
	.string "foreign region or something.$"

DarkRuins_FinalRoom_Text_ArumIntro:
	.string "How incredible!\n"
	.string "You've completed all of my puzzles!\p"
	.string "You are truly interesting, {PLAYER}…\p"
	.string "But you're not just here to complete\n"
	.string "puzzles, are you?\l"
	.string "I promised you a reward…\l"
	.string "But the fun isn't over yet!\n"
	.string "Your final test… is a battle!\p"
	.string "If you can defeat me, then the\n"
	.string "Relic Crown is yours!$"

DarkRuins_FinalRoom_Text_ArumDefeat:
	.string "My, {PLAYER}…\n"
	.string "How strong you are!$"

DarkRuins_FinalRoom_Text_ArumPostBattle:
	.string "Hahaha!\n"
	.string "That battle was the best!\p"
	.string "Not only are you a puzzle genius,\n"
	.string "but you're a seasoned battler too!\p"
	.string "Very well! This is yours!$"

DarkRuins_FinalRoom_Text_ArumNext:
	.string "That is indeed the Relic Crown!\n"
	.string "Take a look at its magnificence!\p"
	.string "It is yours to do whatever you\n"
	.string "please with.\p"
	.string "I was searching for a long time\n"
	.string "for someone who could solve my\l"
	.string "expertly-crafted puzzles.\p"
	.string "And I finally found him.\n"
	.string "That satisifies me.\p"
	.string "Oh, but I'm rambling now.\p"
	.string "Now that the Crown is yours,\n"
	.string "you must be looking to return\l"
	.string "to the surface.\p"
	.string "I'm willing to take you back\n"
	.string "whenever you'd like.\p"
	.string "However, you can't come back,\n"
	.string "so make sure you finish what\l"
	.string "you need to down here.\p"
	.string "Do you understand?\p"
	.string "If there is anything you need\n"
	.string "to still do down here, do it now.$"

DarkRuins_FinalRoom_Text_ArumWantToReturn:
	.string "Would you like to return to the\n"
	.string "surface?$"

DarkRuins_FinalRoom_Text_ArumTakeYourTime:
	.string "Take your time.\n"
	.string "I'm in no rush.$"

DarkRuins_FinalRoom_Text_ArumLetsGo:
	.string "Okay, let's go!$"