@ Trainer text

ShendownPath_Text_LingIntro:
	.string "Aha! Our eyes met!\n"
	.string "Looks like we've got ourselves a battle!$"

ShendownPath_Text_LingDefeat:
	.string "Aw… I was too rash…$"

ShendownPath_Text_LingPostBattle:
	.string "Wild Pokémon around here are pretty\n"
	.string "tame, so any Poké Ball you throw is\l"
	.string "guaranteed to catch something.$"

ShendownPath_Text_BaiIntro:
	.string "Taking the long way to Cho today?\n"
	.string "You must be pretty confident!$"

ShendownPath_Text_BaiDefeat:
	.string "Your confidence is warranted!$"

ShendownPath_Text_BaiPostBattle:
	.string "Living in a place like this is\n"
	.string "hard, but Pokémon make it all\l"
	.string "worth it.$"

ShendownPath_Text_HongIntro: @ 82318A1
	.string "I waited for you because I\n"
	.string "wanted to beat you!$"

ShendownPath_Text_HongDefeat: @ 82318DD
	.string "Looks like I'm the one who's\n"
	.string "getting beat…$"

ShendownPath_Text_HongPostBattle: @ 82318F2
	.string "I really ought to stop battling\n"
	.string "and get back to my dad's farm.$"

WangyongMarsh_Text_KangIntro:
	.string "You're going to see the Oracle?\n"
	.string "Who has time for that?$"

WangyongMarsh_Text_KangDefeat:
	.string "Who has time to battle, even?\n"
	.string "I need to get back to work!$"

WangyongMarsh_Text_KangPostBattle:
	.string "The marshlands are full of nutrients,\n"
	.string "so they're the perfect place for\l"
	.string "gathering plants for compost.$"

WangyongMarsh_Text_FanIntro:
	.string "I almost had that one!\n"
	.string "Why, you…$"

WangyongMarsh_Text_FanDefeat:
	.string "Losing a catch and a battle?\n"
	.string "This is not my day…$"

WangyongMarsh_Text_FanPostBattle:
	.string "You got your fight, so shoo!\n"
	.string "I'm busy here.$"

WangyongMarsh_Text_BolinIntro:
	.string "This is the perfect spot to fish!\n"
	.string "I'm sure of it.$"

WangyongMarsh_Text_BolinDefeat:
	.string "This is the worst spot to battle!\n"
	.string "I'm sure of it.$"

WangyongMarsh_Text_BolinPostBattle:
	.string "Fishing rods are a fisherman's most\n"
	.string "prized possession, you know.\p"
	.string "The rod I'm using now was passed down\n"
	.string "from my great-grandfather, to my\l"
	.string "grandfather, to my father, to me.$"

WangyongMarsh_Text_ChangpuIntro:
	.string "Wachaaa!\p"
	.string "If you get too close, I'm gonna\n"
	.string "kick those Poké Balls out of your\l"
	.string "hands!$"

WangyongMarsh_Text_ChangpuDefeat:
	.string "Finished already?$"

WangyongMarsh_Text_ChangpuPostBattle:
	.string "Well, losing at Pokémon is\n"
	.string "no serious matter at all.\p"
	.string "After all, my strengths lie in my\n"
	.string "mind, body and soul!$"

WangyongMarsh_Text_DandanIntro:
	.string "I caught a Carnivine to help\n"
	.string "me make clothes, but it just\l"
	.string "chews all my fabric to pieces…$"

WangyongMarsh_Text_DandanDefeat:
	.string "Oh, dear!$"

WangyongMarsh_Text_DandanPostBattle:
	.string "Even if my Pokémon can be annoying\n"
	.string "sometimes, I still love them to bits.\p"
	.string "That's just part of being a Trainer,\n"
	.string "right?$"

KimyangRoad_Text_GenIntro:
	.string "Trainer detected!\n"
	.string "Spinarak, let's go!$"

KimyangRoad_Text_GenDefeat:
	.string "No way…\n"
	.string "You're too strong!$"

KimyangRoad_Text_GenPostBattle:
	.string "My favourite Pokémon are all\n"
	.string "Bug-types!\p"
	.string "That's because they evolve early.$"

KimyangRoad_Text_NianIntro:
	.string "A battle, huh?\n"
	.string "Make it quick!$"

KimyangRoad_Text_NianDefeat:
	.string "That was quick indeed!$"

KimyangRoad_Text_NianPostBattle:
	.string "You're a berry farmer?\n"
	.string "Sounds tiring.\p"
	.string "Doesn't a life of relaxing\n"
	.string "fishing sound appealing to you?$"

OracleHill_Text_XiuIntro:
	.string "Check out my adorable little\n"
	.string "Pokémon friends!$"

OracleHill_Text_XiuDefeat:
	.string "Oh, I lost.$"

OracleHill_Text_XiuPostBattle:
	.string "When I get older, I want to\n"
	.string "become the Oracle's apprentice.$"

ZhaounPath_Text_PengfeiIntro:
	.string "I can't find any wild Pokémon…\n"
	.string "That really bugs me!$"

ZhaounPath_Text_PengfeiDefeat:
	.string "Losing bugs me too!$"

ZhaounPath_Text_PengfeiPostBattle:
	.string "There are exotic Bug-type Pokémon\n"
	.string "in this area, so I catch and\l"
	.string "sell them to researchers.$"

ZhaounPath_Text_YaoIntro:
	.string "Hey, stop there!\n"
	.string "I'm going to beat you!$"

ZhaounPath_Text_YaoDefeat:
	.string "No, it can't be!$"

ZhaounPath_Text_YaoPostBattle:
	.string "I'm trying to escape my dad.\n"
	.string "He wants me to be in charge of our\l"
	.string "potato farm, but I don't want to be!$"

TiyuForest_Text_ShiIntro:
	.string "I know all about Bug-type Pokémon.\n"
	.string "People call me the Bug-type guru!$"

TiyuForest_Text_ShiDefeat:
	.string "Knowledge isn't always power, it\n"
	.string "seems…$"

TiyuForest_Text_ShiPostBattle:
	.string "You're researching the ruins?\p"
	.string "Cool. I wonder if there are any\n"
	.string "Bug-type Pokémon living there.$"

TiyuForest_Text_PingIntro:
	.string "Ha! I've ensnared a Trainer!$"

TiyuForest_Text_PingDefeat:
	.string "It was a trap!\n"
	.string "I was the one who was ensnared…$"

TiyuForest_Text_PingPostBattle:
	.string "I catch Bug-type Pokémon to give to\n"
	.string "my big sis, who works as a tailor.$"

TiyuForest_Text_ChuntaoIntro:
	.string "Huh? A battle?\n"
	.string "But I'm trying to weave a dress!$"

TiyuForest_Text_ChuntaoDefeat:
	.string "This really winds me up!$"

TiyuForest_Text_ChuntaoPostBattle:
	.string "Seriously, leave me alone.\n"
	.string "I need to catch up on my work.$"

TiyuForest_Text_DaiyuIntro:
	.string "I'm collecting mushrooms to bring\n"
	.string "back to Cho Village.$"

TiyuForest_Text_DaiyuDefeat:
	.string "I lost? This sucks!$"

TiyuForest_Text_DaiyuPostBattle:
	.string "Selling Tiny Mushrooms is decent\n"
	.string "pocket money, but I need to sell\l"
	.string "Big Mushrooms to live properly.$"

DarkCityEntrance_Text_LuIntro:
	.string "Spirits, be gone!$"

DarkCityEntrance_Text_LuDefeat:
	.string "…Am I cursed?$"

DarkCityEntrance_Text_LuPostBattle:
	.string "Everyone can see ghost Pokémon,\n"
	.string "but I can see ghost humans!$"

DarkCityEntrance_Text_RueIntro:
	.string "Yes… I can see it!\n"
	.string "My victory over you!$"

DarkCityEntrance_Text_RueDefeat:
	.string "Am I a false prophet?$"

DarkCityEntrance_Text_RuePostBattle:
	.string "I heard that Xatu can see into\n"
	.string "the future and past simultaneously.\l"
	.string "I want to catch one…$"

DarkCityEntrance_Text_GuoweiIntro:
	.string "Let us engage in combat, young one!$"

DarkCityEntrance_Text_GuoweiDefeat:
	.string "Very good!$"

DarkCityEntrance_Text_GuoweiPostBattle:
	.string "I'm not sure how you made it down\n"
	.string "here, but your skill is commendable.$"

FarmerHut_Text_TakeRestInBed:
	.string "It's {PLAYER}'s bed…\n"
	.string "Let's take a rest.$"

FarmerHut_Text_ReceivedDedenne:
	.string "{PLAYER} received the {STR_VAR_1}!$"
