@ Trainer text

ShendownPath_Text_LingIntro:
	.string "{JPN}おお！　めが　あった！\n"
	.string "{JPN}いざ　ポケモンしょうぶだ！$"

ShendownPath_Text_LingDefeat:
	.string "{JPN}あまりに　けいそつした…$"

ShendownPath_Text_LingPostBattle:
	.string "{JPN}ここの　やせいポケモンが　めっちゃじゅうじゅんだから\n"
	.string "{JPN}つかまえるのは　かんたんだ！$"

ShendownPath_Text_BaiIntro:
	.string "{JPN}ほんとうに チョむらへ あるきで いっているのか？\n"
	.string "{JPN}じしんが　あるだろうね！$"

ShendownPath_Text_BaiDefeat:
	.string "{JPN}おまえの　じしんは　せいとうかされる…$"

ShendownPath_Text_BaiPostBattle:
	.string "{JPN}ここで　すむのは　きついが　ポケモンと\n"
	.string "{JPN}いっしょに　すむので　かちがある$"

ShendownPath_Text_HongIntro: @ 82318A1
	.string "{JPN}あんたを　たおすために　ここで　まった！$"

ShendownPath_Text_HongDefeat: @ 82318DD
	.string "{JPN}ああ…　わたしがまけた…$"

ShendownPath_Text_HongPostBattle: @ 82318F2
	.string "{JPN}パパの　たんぼへ　かえらなければならない$"

WangyongMarsh_Text_KangIntro:
	.string "{JPN}えー？　せんにんと　あうに　いっている？\n"
	.string "{JPN}だれが　そのための　じかんを　もっているのか？$"

WangyongMarsh_Text_KangDefeat:
	.string "{JPN}だれが　しょうぶの　じかんを　もっているのか？\n"
	.string "{JPN}しごとに　もどるのは　ひつようだ$"

WangyongMarsh_Text_KangPostBattle:
	.string "{JPN}ぬまちの　くさきは　いいえいようげんだ$"

WangyongMarsh_Text_FanIntro:
	.string "{JPN}I almost had that one!\n"
	.string "{JPN}Why, you…$"

WangyongMarsh_Text_FanDefeat:
	.string "{JPN}Losing a catch and a battle?\n"
	.string "{JPN}This is not my day…$"

WangyongMarsh_Text_FanPostBattle:
	.string "{JPN}You got your fight, so shoo!\n"
	.string "{JPN}I'm busy here.$"

WangyongMarsh_Text_BolinIntro:
	.string "{JPN}This is the perfect spot to fish!\n"
	.string "{JPN}I'm sure of it.$"

WangyongMarsh_Text_BolinDefeat:
	.string "{JPN}This is the worst spot to battle!\n"
	.string "{JPN}I'm sure of it.$"

WangyongMarsh_Text_BolinPostBattle:
	.string "{JPN}Fishing rods are a fisherman's most\n"
	.string "{JPN}prized possession, you know.\p"
	.string "{JPN}The rod I'm using now was passed down\n"
	.string "{JPN}from my great-grandfather, to my\l"
	.string "{JPN}grandfather, to my father, to me.$"

WangyongMarsh_Text_ChangpuIntro:
	.string "{JPN}Wachaaa!\p"
	.string "{JPN}If you get too close, I'm gonna\n"
	.string "{JPN}kick those Poké Balls out of your\l"
	.string "{JPN}hands!$"

WangyongMarsh_Text_ChangpuDefeat:
	.string "{JPN}Finished already?$"

WangyongMarsh_Text_ChangpuPostBattle:
	.string "{JPN}Well, losing at Pokémon is\n"
	.string "{JPN}no serious matter at all.\p"
	.string "{JPN}After all, my strengths lie in my\n"
	.string "{JPN}mind, body and soul!$"

WangyongMarsh_Text_DandanIntro:
	.string "{JPN}I caught a Carnivine to help\n"
	.string "{JPN}me make clothes, but it just\l"
	.string "{JPN}chews all my fabric to pieces…$"

WangyongMarsh_Text_DandanDefeat:
	.string "{JPN}Oh, dear!$"

WangyongMarsh_Text_DandanPostBattle:
	.string "{JPN}Even if my Pokémon can be annoying\n"
	.string "{JPN}sometimes, I still love them to bits.\p"
	.string "{JPN}That's just part of being a Trainer,\n"
	.string "{JPN}right?$"

KimyangRoad_Text_GenIntro:
	.string "{JPN}Trainer detected!\n"
	.string "{JPN}Spinarak, let's go!$"

KimyangRoad_Text_GenDefeat:
	.string "{JPN}No way…\n"
	.string "{JPN}You're too strong!$"

KimyangRoad_Text_GenPostBattle:
	.string "{JPN}My favourite Pokémon are all\n"
	.string "{JPN}Bug-types!\p"
	.string "{JPN}That's because they evolve early.$"

KimyangRoad_Text_NianIntro:
	.string "{JPN}A battle, huh?\n"
	.string "{JPN}Make it quick!$"

KimyangRoad_Text_NianDefeat:
	.string "{JPN}That was quick indeed!$"

KimyangRoad_Text_NianPostBattle:
	.string "{JPN}You're a berry farmer?\n"
	.string "{JPN}Sounds tiring.\p"
	.string "{JPN}Doesn't a life of relaxing\n"
	.string "{JPN}fishing sound appealing to you?$"

OracleHill_Text_XiuIntro:
	.string "{JPN}Check out my adorable little\n"
	.string "{JPN}Pokémon friends!$"

OracleHill_Text_XiuDefeat:
	.string "{JPN}Oh, I lost.$"

OracleHill_Text_XiuPostBattle:
	.string "{JPN}When I get older, I want to\n"
	.string "{JPN}become the Oracle's apprentice.$"

ZhaounPath_Text_PengfeiIntro:
	.string "{JPN}I can't find any wild Pokémon…\n"
	.string "{JPN}That really bugs me!$"

ZhaounPath_Text_PengfeiDefeat:
	.string "{JPN}Losing bugs me too!$"

ZhaounPath_Text_PengfeiPostBattle:
	.string "{JPN}There are exotic Bug-type Pokémon\n"
	.string "{JPN}in this area, so I catch and\l"
	.string "{JPN}sell them to researchers.$"

ZhaounPath_Text_YaoIntro:
	.string "{JPN}Hey, stop there!\n"
	.string "{JPN}I'm going to beat you!$"

ZhaounPath_Text_YaoDefeat:
	.string "{JPN}No, it can't be!$"

ZhaounPath_Text_YaoPostBattle:
	.string "{JPN}I'm trying to escape my dad.\n"
	.string "{JPN}He wants me to be in charge of our\l"
	.string "{JPN}potato farm, but I don't want to be!$"

TiyuForest_Text_ShiIntro:
	.string "{JPN}I know all about Bug-type Pokémon.\n"
	.string "{JPN}People call me the Bug-type guru!$"

TiyuForest_Text_ShiDefeat:
	.string "{JPN}Knowledge isn't always power, it\n"
	.string "{JPN}seems…$"

TiyuForest_Text_ShiPostBattle:
	.string "{JPN}You're researching the ruins?\p"
	.string "{JPN}Cool. I wonder if there are any\n"
	.string "{JPN}Bug-type Pokémon living there.$"

TiyuForest_Text_PingIntro:
	.string "{JPN}Ha! I've ensnared a Trainer!$"

TiyuForest_Text_PingDefeat:
	.string "{JPN}It was a trap!\n"
	.string "{JPN}I was the one who was ensnared…$"

TiyuForest_Text_PingPostBattle:
	.string "{JPN}I catch Bug-type Pokémon to give to\n"
	.string "{JPN}my big sis, who works as a tailor.$"

TiyuForest_Text_ChuntaoIntro:
	.string "{JPN}Huh? A battle?\n"
	.string "{JPN}But I'm trying to weave a dress!$"

TiyuForest_Text_ChuntaoDefeat:
	.string "{JPN}This really winds me up!$"

TiyuForest_Text_ChuntaoPostBattle:
	.string "{JPN}Seriously, leave me alone.\n"
	.string "{JPN}I need to catch up on my work.$"

TiyuForest_Text_DaiyuIntro:
	.string "{JPN}I'm collecting mushrooms to bring\n"
	.string "{JPN}back to Cho Village.$"

TiyuForest_Text_DaiyuDefeat:
	.string "{JPN}I lost? This sucks!$"

TiyuForest_Text_DaiyuPostBattle:
	.string "{JPN}Selling Tiny Mushrooms is decent\n"
	.string "{JPN}pocket money, but I need to sell\l"
	.string "{JPN}Big Mushrooms to live properly.$"

DarkCityEntrance_Text_LuIntro:
	.string "{JPN}Spirits, be gone!$"

DarkCityEntrance_Text_LuDefeat:
	.string "{JPN}…Am I cursed?$"

DarkCityEntrance_Text_LuPostBattle:
	.string "{JPN}Everyone can see ghost Pokémon,\n"
	.string "{JPN}but I can see ghost humans!$"

DarkCityEntrance_Text_RueIntro:
	.string "{JPN}Yes… I can see it!\n"
	.string "{JPN}My victory over you!$"

DarkCityEntrance_Text_RueDefeat:
	.string "{JPN}Am I a false prophet?$"

DarkCityEntrance_Text_RuePostBattle:
	.string "{JPN}I heard that Xatu can see into\n"
	.string "{JPN}the future and past simultaneously.\l"
	.string "{JPN}I want to catch one…$"

DarkCityEntrance_Text_GuoweiIntro:
	.string "{JPN}Let us engage in combat, young one!$"

DarkCityEntrance_Text_GuoweiDefeat:
	.string "{JPN}Very good!$"

DarkCityEntrance_Text_GuoweiPostBattle:
	.string "{JPN}I'm not sure how you made it down\n"
	.string "{JPN}here, but your skill is commendable.$"

FarmerHut_Text_TakeRestInBed:
	.string "{JPN}It's {PLAYER}'s bed…\n"
	.string "{JPN}Let's take a rest.$"

FarmerHut_Text_ReceivedDedenne:
	.string "{JPN}{PLAYER} received the {STR_VAR_1}!$"
